import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clubsRouter from "./clubs";
import squadRouter from "./squad";
import proxyRouter from "./proxy";
import playersRouter from "./players";
import adminRouter from "./admin";
import adminPanelRouter from "./adminPanel";
import noticiasRouter from "./noticias";
import storageRouter from "./storage";
import diretoriaRouter from "./diretoria";
import careersRouter from "./careers";
import gamedataRouter from "./gamedata";
import portalsRouter from "./portals";
import authRouter from "./auth";
import stripeRouter from "./stripe";
import lemonRouter from "./lemon";
import leaguesRouter from "./leagues";
import communityRouter from "./community";
import communityAdminRouter from "./communityAdmin";

const router: IRouter = Router();

router.use(authRouter);
router.use(stripeRouter);
router.use(lemonRouter);
router.use(healthRouter);
router.use(clubsRouter);
router.use(squadRouter);
router.use(proxyRouter);
router.use(playersRouter);
router.use(adminRouter);
router.use(adminPanelRouter);
router.use(noticiasRouter);
router.use(storageRouter);
router.use(diretoriaRouter);
router.use(careersRouter);
router.use(gamedataRouter);
router.use(portalsRouter);
router.use(leaguesRouter);
router.use(communityRouter);
router.use(communityAdminRouter);

export default router;
