import type { PersonalityStyle } from "@/types/diretoria";

export interface ClubPresidentData {
  name: string;
  personality: PersonalityStyle;
  patience: number;
  description: string;
}

export const CLUB_PRESIDENTS: Record<number, ClubPresidentData> = {
  541: { name: "Florentino Pérez", personality: "exigente", patience: 55, description: "Presidente galáctico do Real Madrid, sempre obcecado com títulos e grandes contratações. Exige excelência absoluta do técnico e não aceita mediocridade. Reage mal a sequências negativas, mas respeita treinadores que mantêm a identidade vencedora do clube. É um negociador implacável e tem enorme influência no futebol mundial." },
  529: { name: "Joan Laporta", personality: "emocional", patience: 50, description: "Presidente apaixonado do FC Barcelona, vive intensamente cada resultado do clube. Discursa sobre identidade, Cruyffismo e futebol de ataque em todas as ocasiões. Pode ser impulsivo e mudar de posição rapidamente dependendo dos resultados. Valoriza treinadores que entendem o DNA do Barça, mas cobra resultados no Camp Nou." },
  530: { name: "Enrique Cerezo", personality: "diplomatico", patience: 65, description: "Presidente experiente do Atlético de Madrid, prefere a estabilidade à espetacularidade. Gere conflitos internos com habilidade e raramente entra em confronto direto com o técnico. Tem paciência razoável para projetos de longo prazo, mas espera que o clube seja sempre competitivo. Valoriza lealdade e comprometimento acima de tudo." },
  536: { name: "José María del Nido Carrasco", personality: "emocional", patience: 50, description: "Presidente do Sevilla FC, filho de um dos maiores presidentes da história do clube. Apaixonado pelo clube e pela sua tradição europeia. Envolve-se emocionalmente nos resultados e pode ser impulsivo em momentos de crise. Valoriza a identidade sevilhana e o futebol de alta intensidade que caracterizou os anos dourados do clube na Europa." },
  532: { name: "Layhoon Chan", personality: "conservador", patience: 65, description: "Presidente do Valencia CF, representante dos interesses do proprietário no clube. Gere com cautela financeira e prefere evitar confrontos públicos. Tem paciência com projetos graduais, mas enfrenta pressão constante da torcida local. Valoriza estabilidade e busca recuperar a relevância histórica do clube na La Liga." },
  533: { name: "Fernando Roig Negueroles", personality: "conservador", patience: 70, description: "Presidente do Villarreal CF, filho do fundador do projeto. Administra o clube de forma familiar e sustentável, valorizando o crescimento orgânico. Tem paciência notável com projetos de longo prazo e confia no trabalho do técnico. Prefere desenvolver talentos a fazer gastos astronômicos, consolidando o submarino amarelo na elite." },
  531: { name: "Jon Uriarte", personality: "diplomatico", patience: 65, description: "Presidente do Athletic Club de Bilbao, guardião da filosofia cantera. Defensor intransigente da política de contratar apenas jogadores bascos ou formados na academia do clube. Tem paciência com o processo de desenvolvimento, mas exige que o Athletic jogue o futebol agressivo e comprometido que define o clube. Valoriza a identidade cultural acima de resultados imediatos." },
  543: { name: "Ángel Haro", personality: "diplomatico", patience: 68, description: "Presidente do Real Betis Balompié, empresário andaluz com gestão equilibrada. Busca manter o clube competitivo sem sacrificar a estabilidade financeira. Tem paciência com projetos de médio prazo e valoriza o futebol de qualidade que o Betis praticou recentemente. Entende que a torcida verdiblanca exige presença nas competições europeias." },
  548: { name: "Jokin Aperribay", personality: "analitico", patience: 70, description: "Presidente da Real Sociedad, empresário vasco metódico e criterioso. Construiu um modelo de gestão baseado em formação interna e análise de dados. Tem grande paciência com projetos de longo prazo e valoriza a identidade txuri-urdin. Cobra comprometimento técnico e tático, mas entende os ciclos naturais do futebol." },
  546: { name: "Ángel Torres", personality: "exigente", patience: 50, description: "Presidente do Getafe CF, um dos dirigentes mais intensos da La Liga. Não tem papas na língua e frequentemente entra em conflito com árbitros e outros clubes. Exige que o Getafe seja sempre competitivo e organizado defensivamente. Tem paciência limitada com derrotas e pode ser vocal na sua insatisfação." },
  558: { name: "Carlos Mouriño", personality: "emocional", patience: 55, description: "Presidente do Celta de Vigo, empresário apaixonado pelo clube galego. Vive intensamente cada resultado e não esconde os sentimentos perante a imprensa. Valoriza o futebol ofensivo e a formação de jovens talentos. Tem paciência moderada, mas pode ser impulsivo em momentos de crise para a equipe." },
  489: { name: "Paolo Scaroni", personality: "analitico", patience: 60, description: "Presidente do AC Milan com perfil empresarial e racional. Toma decisões baseadas em dados financeiros e de desempenho. Reage com frieza a resultados ruins, mas exige explicações claras do corpo técnico. Valoriza a recuperação histórica do clube e não tolera gestão amadora." },
  505: { name: "Giuseppe Marotta", personality: "analitico", patience: 70, description: "CEO e presidente-executivo da Inter de Milão, referência em gestão esportiva italiana. Metódico, criterioso e sempre bem-informado sobre mercado de transferências. Dá suporte ao técnico desde que os números justifiquem as escolhas. Tem visão estratégica de longo prazo e raramente entra em pânico em momentos difíceis." },
  496: { name: "Gianluca Ferrero", personality: "conservador", patience: 65, description: "Presidente da Juventus num momento de reconstrução do clube. Adota postura cautelosa e prioriza a sustentabilidade financeira após anos de instabilidade. Apoia o projeto técnico enquanto vê evolução, mas é sensível à pressão da torcida fanática bianconera. Valoriza a tradição e os títulos históricos do clube." },
  492: { name: "Aurelio De Laurentiis", personality: "emocional", patience: 40, description: "Presidente temperamental do SSC Napoli, produtor cinematográfico de coração apaixonado. Envolve-se diretamente em decisões técnicas e não hesita em expressar insatisfação publicamente. Sequências negativas o deixam furioso e pode agir de forma impulsiva. No entanto, quando as coisas vão bem, é extremamente generoso e entusiasmado." },
  497: { name: "Dan Friedkin", personality: "conservador", patience: 70, description: "Presidente da AS Roma, investidor americano que assumiu o clube com ambições europeias. Gere o clube de forma discreta, preferindo não expor sua visão publicamente. Tem paciência com projetos de longo prazo, mas espera profissionalismo e dedicação. Entende a importância cultural do futebol romano e respeita a tradição do clube." },
  487: { name: "Claudio Lotito", personality: "exigente", patience: 45, description: "Presidente da SS Lazio, político e empresário com estilo de liderança autoritário. Controla o clube com mão-de-ferro e não hesita em confrontar técnicos ou jogadores quando os resultados desagradam. É detalhista e exige relatórios constantes sobre a situação do elenco. Extremamente exigente, mas leal aos que entregam resultados." },
  499: { name: "Antonio Percassi", personality: "diplomatico", patience: 72, description: "Presidente da Atalanta, empresário bergamasco que transformou o clube numa potência europeia. Tem visão de longo prazo e paciência para projetos consistentes. Valoriza a formação de jovens e o futebol de ataque que se tornou marca registrada do clube. Apoia o técnico desde que o estilo de jogo continue a encantar e produzir resultados." },
  502: { name: "Rocco Commisso", personality: "emocional", patience: 52, description: "Presidente da Fiorentina, empresário ítalo-americano apaixonado pelo clube viola. Investe de forma ambiciosa e tem grande expectativa de retorno. Pode ser emocional e vocal perante a mídia quando as coisas não correm bem. Valoriza o compromisso com as cores viola e quer ver a Fiorentina competindo nas competições europeias regularmente." },
  503: { name: "Urbano Cairo", personality: "analitico", patience: 60, description: "Presidente do Torino FC, editor de mídia com perfil analítico e cauteloso. Administra o clube com foco na sustentabilidade financeira e não costuma fazer grandes gastos. Tem paciência moderada e valoriza treinadores que desenvolvem jovens e organizam bem a equipe. Entende que o Torino precisa ser competitivo sem comprometer as contas." },
  500: { name: "Joey Saputo", personality: "conservador", patience: 68, description: "Presidente do Bologna FC, empresário canadense que transformou o clube. Gere de forma profissional com foco no desenvolvimento sustentável e na formação de talentos. Tem paciência com projetos de longo prazo e valoriza o crescimento gradual. Entende a importância histórica do clube para a cidade e quer consolidá-lo na elite italiana." },
  490: { name: "Alberto Zangrillo", personality: "diplomatico", patience: 65, description: "Presidente do Genoa CFC, cardiologista e político italiano. Gere o clube mais antigo da Itália com senso de responsabilidade histórica. Tem perfil diplomático e mantém bom relacionamento com imprensa e torcida. Valoriza a tradição genoana e espera que o clube seja competitivo sem comprometer sua identidade." },
  494: { name: "Giampaolo Pozzo", personality: "analitico", patience: 70, description: "Presidente do Udinese Calcio, empresário que controla o clube há décadas. Especialista em descobrir talentos e vendê-los para grandes clubes europeus. Tem visão clara do modelo de negócio do Udinese e paciência para projetos sustentáveis. Valoriza gestão econômica sólida e formação de jovens promissores." },
  157: { name: "Herbert Hainer", personality: "diplomatico", patience: 65, description: "Presidente do Bayern de Munique, ex-CEO da Adidas com perfil corporativo e polido. Mantém a estrutura vencedora do clube funcionando com profissionalismo. Evita conflitos públicos e prefere resolver questões internamente. Tem expectativas altíssimas dada a história do clube, mas dá suporte ao projeto técnico enquanto os resultados se mantêm competitivos." },
  165: { name: "Hans-Joachim Watzke", personality: "emocional", patience: 55, description: "CEO do Borussia Dortmund, voz da identidade amarelo-preta. Apaixonado pelo clube e pela conexão com a torcida do Muro Amarelo. Envolve-se emocionalmente nos resultados e cobra o mesmo nível de comprometimento do corpo técnico. Valoriza o futebol de ataque e as estrelas reveladas pela academia do BVB." },
  173: { name: "Oliver Mintzlaff", personality: "agressivo", patience: 48, description: "CEO do RB Leipzig, executivo com DNA Red Bull de alta performance. Orientado para resultados e data analytics, não tolera mediocridade. Tem pouca paciência para sequências ruins e pode tomar decisões rápidas. Valoriza o modelo de jogo intenso e progressivo que é a marca do projeto Leipzig no futebol alemão." },
  168: { name: "Fernando Carro", personality: "exigente", patience: 50, description: "CEO do Bayer Leverkusen numa era de ambições renovadas. Meticuloso e altamente exigente com a performance coletiva. Após o título histórico da Bundesliga, as expectativas no clube subiram muito. Não aceita regressão e pressiona o técnico para manter padrões elevados. Analisa cada detalhe das atuações do elenco." },
  172: { name: "Claus Vogt", personality: "diplomatico", patience: 65, description: "Presidente do VfB Stuttgart, eleito pelos sócios do clube. Gere com transparência e busca manter o Stuttgart como clube do povo. Tem paciência moderada e valoriza o futebol jovem e progressivo. Quer ver o Stuttgart competitivo na Bundesliga e na Europa sem perder sua essência de clube de base sólida." },
  169: { name: "Peter Fischer", personality: "emocional", patience: 55, description: "Presidente do Eintracht Frankfurt, um dos dirigentes mais apaixonados do futebol alemão. Não tem medo de se posicionar politicamente e defende os valores do clube com intensidade. Vive os resultados intensamente e quer que o Eintracht seja sempre competitivo. A aventura europeia recente elevou as expectativas da torcida e da diretoria." },
  160: { name: "Marcel Schäfer", personality: "analitico", patience: 62, description: "Diretor esportivo do VfL Wolfsburg, ex-jogador com perfil analítico. Administra o clube de forma profissional com apoio do grupo Volkswagen. Valoriza organização, dados e planejamento de longo prazo. Tem paciência razoável, mas espera que o técnico mantenha a equipe competitiva e organizada na Bundesliga." },
  163: { name: "Roland Virkus", personality: "conservador", patience: 68, description: "Diretor geral do Borussia Monchengladbach, gestor experiente com foco em sustentabilidade. Administra o clube priorizando equilíbrio financeiro e desenvolvimento de jovens. Tem paciência com processos de reconstrução, mas sente a pressão de manter o Gladbach na Bundesliga. Valoriza a história do clube e quer recuperar seu prestígio europeu." },
  167: { name: "Oke Göttlich", personality: "diplomatico", patience: 60, description: "Presidente do FC St. Pauli, clube com forte identidade política e social em Hamburgo. Defende os valores progressistas do clube com convicção. Tem paciência com projetos que respeitem a identidade do clube, mas cobra competitividade. O acesso recente à Bundesliga elevou as expectativas para um clube que tem muito mais do que futebol." },
  162: { name: "Hubertus Hess-Grunewald", personality: "analitico", patience: 65, description: "Presidente do Werder Bremen, clube com história rica na Bundesliga alemã. Administra com critério e preza pela formação de jovens talentos. Tem paciência moderada e valoriza o futebol ofensivo que sempre caracterizou o Werder. Cobra comprometimento e resultados condizentes com o potencial do clube no futebol alemão." },
  182: { name: "Dirk Zingler", personality: "emocional", patience: 55, description: "Presidente do Union Berlin, clube com identidade única e torcida apaixonadíssima. Construiu um projeto surpreendente que levou o Union ao futebol europeu. Vive intensamente cada jogo e é muito próximo da torcida. Valoriza o comprometimento com a camisa e o espírito de equipe acima de nomes individuais." },
  85: { name: "Nasser Al-Khelaïfi", personality: "agressivo", patience: 35, description: "Presidente do Paris Saint-Germain e figura do Qatar Sports Investments. Movimenta o futebol mundial com seu poder financeiro e ambição desmedida. Não aceita nada menos que a Liga dos Campeões e pressiona o técnico constantemente. Pode ser impulsivo e mudar a diretriz do clube abruptamente quando as expectativas não são atendidas. Altamente influente no cenário político do futebol europeu." },
  81: { name: "Pablo Longoria", personality: "analitico", patience: 60, description: "Presidente do Olympique de Marseille, jovem dirigente espanhol com formação em análise de dados. Construiu uma reputação como descobridor de talentos e gestor inovador. Tem visão estratégica clara e paciência para projetos coerentes. Valoriza futebol de ataque e identidade competitiva, entendendo a enorme pressão da torcida marselhesa." },
  80: { name: "John Textor", personality: "agressivo", patience: 45, description: "Proprietário do Olympique Lyonnais e do Eagle Football Group. Empresário americano com ambições globais no futebol. Não hesita em confrontar publicamente adversários e reguladores. Espera resultados expressivos do investimento realizado no Lyon e pode ser impulsivo quando os resultados frustrarem suas expectativas enormes." },
  91: { name: "Dmitry Rybolovlev", personality: "exigente", patience: 50, description: "Presidente do AS Monaco, bilionário russo que investiu fortemente no clube do principado. Tem grandes expectativas e não aceita o Monaco fora das primeiras posições da Ligue 1. Costuma intervir diretamente nas decisões quando os resultados não satisfazem. Valoriza o futebol jovem e a formação de talentos que podem ser vendidos com lucro." },
  84: { name: "Jean-Pierre Rivère", personality: "diplomatico", patience: 65, description: "Presidente do OGC Nice, dirigente experiente que trouxe estabilidade ao clube da Côte d'Azur. Gere com equilíbrio entre ambições esportivas e realidade financeira. Tem paciência com projetos de médio prazo e valoriza o desenvolvimento de jovens. O investimento dos donos ingleses elevou as expectativas de um clube que quer ser regular na Europa." },
  116: { name: "Joseph Oughourlian", personality: "analitico", patience: 68, description: "Presidente do RC Lens, investidor com visão de longo prazo para o clube mineiro. Transformou o Lens numa força surpreendente da Ligue 1. Valoriza coesão de grupo e consistência. Tem paciência com o projeto, mas espera que o clube se mantenha competitivo e próximo às primeiras posições do campeonato." },
  79: { name: "Olivier Létang", personality: "exigente", patience: 52, description: "Presidente do LOSC Lille, dirigente ambicioso que quer devolver o clube ao topo do futebol francês. Não esconde suas expectativas de formar equipes capazes de competir na Champions League. Cobra constantemente do técnico resultados que justifiquem o investimento na reconstrução do elenco. Valoriza o modelo de revelação de talentos pelo qual o Lille é reconhecido mundialmente." },
  40: { name: "Tom Werner", personality: "conservador", patience: 60, description: "Chairman do Liverpool FC, americano que representa a FSG na Inglaterra. Toma decisões com base em análise de dados e sustentabilidade financeira. Não costuma fazer movimentos impulsivos no mercado, preferindo o desenvolvimento de talentos. Dá suporte ao projeto técnico no longo prazo, mas espera consistência nos resultados da Premier League." },
  42: { name: "Stan Kroenke", personality: "analitico", patience: 75, description: "Proprietário e presidente do Arsenal, empresário americano do ramo esportivo. Mantém distância da gestão diária e delega decisões esportivas à diretoria especializada. Tem paciência considerável para projetos de longo prazo e investe progressivamente na modernização do clube. Valoriza estabilidade financeira e crescimento sustentável." },
  49: { name: "Todd Boehly", personality: "agressivo", patience: 40, description: "Co-proprietário e co-presidente executivo do Chelsea. Empresário americano que chegou com investimentos massivos e ambições imediatas. Envolveu-se diretamente em contratações e pode ser impulsivo nas decisões. Espera resultados rápidos em troca dos investimentos realizados e não tem paciência prolongada com sequências negativas." },
  47: { name: "Daniel Levy", personality: "analitico", patience: 55, description: "Chairman do Tottenham Hotspur, negociador habilidoso e profundamente detalhista. Controla finanças com rigor e raramente aceita pagar além do considerado justo. Tem expectativas altas, mas tende a apoiar o técnico por um período razoável. Valoriza desenvolvimento de elenco e eficiência financeira no mercado de transferências." },
  33: { name: "Jim Ratcliffe", personality: "exigente", patience: 45, description: "Co-proprietário do Manchester United com mandato para recuperar o clube de uma crise longa. Perfil de empresário de alta performance, acostumado com eficiência e resultados. Exige que o clube volte a ser referência mundial no menor tempo possível. Não tem paciência para desculpas e cobra comprometimento total do técnico e do elenco." },
  34: { name: "Yasir Al-Rumayyan", personality: "diplomatico", patience: 70, description: "Presidente do Newcastle United, representante do PIF saudita. Toma decisões estratégicas de forma deliberada e mantém perfil discreto. Entende que o projeto de reconstrução do clube é de longo prazo e dá suporte ao corpo técnico enquanto vê progresso. Tem ambições enormes para o clube, mas age com paciência de investidor estratégico." },
  50: { name: "Khaldoon Al Mubarak", personality: "exigente", patience: 45, description: "Presidente do Manchester City, representante dos investidores de Abu Dhabi. Articulado e ambicioso, exige que o clube mantenha os mais altos padrões mundiais. Tem foco absoluto em títulos e não aceita regressão. Dá suporte ao técnico enquanto os resultados confirmam o projeto vencedor, mas espera dominância constante." },
  66: { name: "Nassef Sawiris", personality: "diplomatico", patience: 68, description: "Co-proprietário do Aston Villa, bilionário egípcio-britânico com ambições europeias. Investiu fortemente no clube e quer consolidar o Villa entre os grandes da Premier League. Tem paciência com projetos consistentes e valoriza o desenvolvimento gradual. Entende que levar o Villa de volta à Europa foi um passo histórico e quer ir além." },
  48: { name: "Daniel Kretinsky", personality: "conservador", patience: 65, description: "Co-proprietário do West Ham United, empresário tcheco do setor de energia. Tem visão de longo prazo para o clube londrino e valoriza a estabilidade. Não costuma fazer intervenções públicas e deixa a gestão esportiva para os profissionais. Cobra resultados condizentes com os investimentos realizados no novo estádio e no elenco." },
  51: { name: "Tony Bloom", personality: "analitico", patience: 72, description: "Dono e presidente do Brighton & Hove Albion, referência global em análise de dados no futebol. Construiu um modelo de gestão baseado em data analytics que se tornou referência na Premier League. Tem grande paciência com projetos alinhados à filosofia do clube. Valoriza desenvolvimento de jogadores e eficiência nas transferências." },
  39: { name: "Jeff Shi", personality: "diplomatico", patience: 68, description: "Presidente do Wolverhampton Wanderers, representante da Fosun International. Administra o clube com perfil discreto e visão de longo prazo. Tem paciência com projetos consistentes e valoriza o futebol organizado. Quer consolidar os Wolves como clube relevante da Premier League com uma identidade clara de jogo." },
  45: { name: "Bill Kenwright", personality: "emocional", patience: 58, description: "Presidente do Everton FC, toffee de coração e dirigente histórico do clube. Apaixonado pelo clube e pela torcida de Goodison Park. Sente profundamente cada resultado e cobra comprometimento com a camisa azul. Tem paciência moderada, mas a pressão para o clube fugir da zona de rebaixamento é intensa e constante." },
  52: { name: "Steve Parish", personality: "diplomatico", patience: 63, description: "Co-proprietário e presidente do Crystal Palace FC. Torcedor histórico do clube que se tornou dirigente. Tem equilíbrio entre paixão pelo clube e visão empresarial. Valoriza a identidade de Selhurst Park e quer ver o Palace competitivo na Premier League sem comprometer a saúde financeira do clube." },
  36: { name: "Shahid Khan", personality: "conservador", patience: 70, description: "Proprietário do Fulham FC, empresário paquistanês-americano do setor automotivo. Tem visão de longo prazo e investe de forma progressiva no clube londrino. Dá suporte ao projeto técnico enquanto vê organização e desenvolvimento. Valoriza a permanência do Fulham na Premier League como base para um projeto ambicioso." },
  55: { name: "Matthew Benham", personality: "analitico", patience: 70, description: "Dono do Brentford FC, especialista em modelagem matemática e apostas esportivas. Construiu um dos modelos de gestão mais inovadores do futebol inglês, baseado em dados e análise estatística. Tem paciência com processos bem fundamentados. Valoriza a eficiência e a coerência do modelo de gestão que levou o Brentford à Premier League." },
  65: { name: "Evangelos Marinakis", personality: "exigente", patience: 48, description: "Proprietário do Nottingham Forest, armador grego com grandes ambições para o clube inglês. Investe pesado e espera resultados rápidos em troca. Não é conhecido pela paciência e pode ser determinante nas decisões do clube. Quer ver o Forest de volta às glórias europeias e não aceita que o clube lute contra o rebaixamento." },
  46: { name: "Aiyawatt Srivaddhanaprabha", personality: "diplomatico", patience: 65, description: "Presidente do Leicester City, filho do falecido fundador do projeto vencedor. Mantém a visão do pai de construir um clube sólido e competitivo na Premier League. Tem paciência com projetos de longo prazo e valoriza a família Leicester. Após o histórico título de 2016, quer ver o clube de volta à elite inglesa após a passagem pela Championship." },
  35: { name: "Bill Foley", personality: "analitico", patience: 63, description: "Proprietário do AFC Bournemouth, investidor americano com portfólio esportivo diversificado. Tem abordagem analítica e valoriza eficiência. Dá suporte ao projeto técnico enquanto o clube permanece competitivo na Premier League. Espera que o Bournemouth consolide sua presença na elite inglesa com futebol organizado." },
  41: { name: "Dragan Solak", personality: "agressivo", patience: 50, description: "Proprietário do Southampton FC, empresário sérvio que investiu no clube da Premier League. Tem expectativas altas após os investimentos realizados no elenco e na infraestrutura. Pode ser impulsivo em momentos de crise e cobra alta performance do corpo técnico. Quer ver o Southampton estabilizado na Premier League." },
  57: { name: "Mark Detmer", personality: "conservador", patience: 68, description: "Co-proprietário do Ipswich Town, americano do projeto Gamechanger 20. Geriu o projeto que levou o Ipswich do terceiro nível ao topo do futebol inglês em poucos anos. Tem paciência com o projeto de desenvolvimento e valoriza a consistência. Entende que a adaptação à Premier League é um processo e dá suporte ao técnico." },
  127: { name: "Rodrigo Dunshee", personality: "exigente", patience: 50, description: "Presidente do Clube de Regatas do Flamengo, advogado e dirigente de longa data. Representa as ambições nacionais e internacionais do maior clube do Brasil. Exige títulos e não aceita mediocridade, dada a dimensão histórica e financeira do Flamengo. Valoriza o futebol ofensivo e cobra postura vencedora em todos os jogos." },
  121: { name: "Leila Pereira", personality: "agressivo", patience: 40, description: "Presidente da SE Palmeiras, empresária dona da Crefisa. Investiu massivamente no clube e cobra resultados proporcionais aos recursos aplicados. É direta, impulsiva e não hesita em manifestar insatisfação publicamente. Tem expectativas altíssimas e pode ser implacável com técnicos que não entregam títulos." },
  131: { name: "Augusto Melo", personality: "diplomatico", patience: 60, description: "Presidente do Sport Club Corinthians Paulista, político experiente no ambiente clube. Navega entre diferentes grupos de torcidas e interesses. Tenta equilibrar as demandas esportivas com as limitações financeiras do clube. Tem paciência moderada e valoriza a lealdade dos jogadores com a camisa alvinegra." },
  137: { name: "Julio Casares", personality: "conservador", patience: 65, description: "Presidente do São Paulo Futebol Clube, médico e dirigente respeitado. Administra o clube com foco na recuperação financeira e esportiva após anos difíceis. Dá suporte ao projeto técnico enquanto vê evolução, mas cobra competitividade. Valoriza a história tricolor e busca devolver o São Paulo ao topo do futebol brasileiro." },
  136: { name: "Marcelo Teixeira", personality: "emocional", patience: 55, description: "Presidente do Santos FC, personagem histórico do clube praiano. Apaixonado pelo futebol de ataque e pela tradição santista. Cobra que o Santos jogue bonito e seja competitivo, mesmo em momentos de reconstrução. Reage mal a derrotas dentro da Vila Belmiro e pode ser vocal na sua insatisfação com a imprensa." },
  118: { name: "Alberto Guerra", personality: "analitico", patience: 60, description: "Presidente do Grêmio Foot-Ball Porto Alegrense, dirigente focado na reestruturação do clube. Analisa o desempenho com dados e tem postura racional. Dá suporte técnico enquanto vê processo evolutivo, mas cobra competitividade na Série A. Valoriza as categorias de base e a identidade defensiva que marcou o clube historicamente." },
  119: { name: "Alessandro Barcellos", personality: "diplomatico", patience: 65, description: "Presidente do Sport Club Internacional, ex-goleiro e dirigente carismático. Transita bem entre torcida, jogadores e imprensa. Tem paciência com projetos de desenvolvimento e valoriza o equilíbrio dentro do grupo. Cobra comprometimento com a camisa vermelha e quer ver o Inter brigando por títulos nacionais." },
  110: { name: "Sérgio Coelho", personality: "exigente", patience: 50, description: "Presidente do Clube Atlético Mineiro, dirigente ambicioso que conduziu o clube à Copa Libertadores. Não se contenta com resultados mediocres e exige que o Galo seja protagonista em todas as competições. Tem paciência limitada com sequências negativas e pode ser vocal na sua cobrança ao corpo técnico. Valorizou muito os títulos recentes." },
  104: { name: "Pedro Lourenço", personality: "agressivo", patience: 45, description: "Presidente do Cruzeiro Esporte Clube, empresário que assumiu o clube na SAF e investiu pesado na reabilitação. Tem perfil empreendedor e não hesita em tomar decisões rápidas. Espera retorno imediato do investimento em forma de títulos e projeção nacional. Cobra alta performance e pode ser impulsivo quando os resultados frustram." },
  114: { name: "John Textor", personality: "agressivo", patience: 45, description: "Presidente do Botafogo de Futebol e Regatas, empresário americano dono do Eagle Football Group. Movimenta o clube com recursos internacionais e ambições de escala global. Não hesita em confrontar a mídia e dirigentes rivais. Espera resultados expressivos dos investimentos realizados e pode ser impulsivo em momentos de pressão." },
  130: { name: "Mário Bittencourt", personality: "diplomatico", patience: 60, description: "Presidente do Fluminense Football Club, advogado e dirigente articulado. Administra bem as relações políticas no futebol brasileiro. Tem paciência com projetos de longo prazo e valoriza a identidade do Fluminense. Cobra competitividade mas entende os ciclos do futebol. Valoriza muito o Maracanã e a tradição carioca do clube." },
  133: { name: "Pedrinho", personality: "emocional", patience: 52, description: "Presidente do Club de Regatas Vasco da Gama, ex-jogador e dirigente apaixonado. Vive intensamente os resultados do clube cruzmaltino e não esconde seus sentimentos. Valoriza a grandeza histórica do Vasco e cobra que o clube ocupe posição de destaque no futebol brasileiro. Tem paciência moderada mas pode ser vocal em momentos difíceis." },
  122: { name: "Alex Santiago", personality: "conservador", patience: 65, description: "Presidente do Fortaleza Esporte Clube, dirigente que conduziu o clube a uma ascensão histórica. Administra com equilíbrio financeiro e investe de forma criteriosa. Tem paciência com projetos consistentes e valoriza o futebol organizado e competitivo. Cobra que o Fortaleza mantenha sua relevância nacional conquistada nos últimos anos." },
  111: { name: "Guilherme Bellintani", personality: "diplomatico", patience: 62, description: "Presidente do Esporte Clube Bahia, advogado e dirigente moderno. Administra bem as relações políticas e institucionais do clube. Tem paciência moderada e valoriza o desenvolvimento do futebol baiano. Cobra que o Bahia seja competitivo e ocupe posição de destaque no cenário nacional, representando o Nordeste com qualidade." },
  138: { name: "Adson Batista", personality: "exigente", patience: 48, description: "Presidente do Atlético Goianiense, empresário e dirigente com perfil exigente. Investe no clube com expectativas de resultados rápidos. Não tem muita paciência com sequências negativas e pode ser direto na cobrança ao corpo técnico. Quer ver o Dragão firme na Série A e competitivo nas copas nacionais." },
  108: { name: "Delfim Peixoto", personality: "conservador", patience: 65, description: "Presidente do América Mineiro, dirigente com gestão cautelosa e focada na sustentabilidade. Administra o clube dentro de suas possibilidades e valoriza a permanência na Série A como conquista importante. Tem paciência com processos de desenvolvimento e cobra comprometimento dos jogadores com a identidade do coelho." },
  212: { name: "André Villas-Boas", personality: "analitico", patience: 62, description: "Presidente do FC Porto, ex-treinador e técnico que conhece o futebol profundamente. Tem visão analítica das contratações e do jogo. Cobra que o Porto mantenha a hegemonia no futebol português e seja competitivo na Champions League. Valoriza o desenvolvimento de jovens talentos que possam ser vendidos com lucro para a Europa." },
  211: { name: "Rui Costa", personality: "exigente", patience: 52, description: "Presidente do Sport Lisboa e Benfica, lenda do clube que assumiu a direção. Tem expectativas altíssimas e não aceita que o Benfica perca a liderança do futebol português. Exige títulos nacionais e participação ativa na Champions League. Pode ser emocional em entrevistas e não hesita em pressionar o corpo técnico." },
  228: { name: "Frederico Varandas", personality: "diplomatico", patience: 65, description: "Presidente do Sporting CP, médico que assumiu o clube num momento difícil. Trouxe equilíbrio financeiro e construiu um projeto vencedor. Tem paciência com processos bem estruturados e valoriza o desenvolvimento de jovens pela academia. Cobra competitividade nacional e internacional, mas entende os ciclos do futebol." },
  217: { name: "António Salvador", personality: "conservador", patience: 68, description: "Presidente do Sporting Clube de Braga, empresário com visão de longo prazo. Transformou o Braga numa força regular do futebol europeu. Tem paciência com projetos sustentáveis e valoriza a revelação de jovens talentos. Cobra que o Braga mantenha sua posição no top 3 português e represente bem o país na Europa." },
  194: { name: "Jan van Halst", personality: "diplomatico", patience: 62, description: "Presidente do AFC Ajax, clube com tradição de revelação de talentos mundialmente. Gere num momento de reconstrução após anos difíceis. Tem paciência com o processo e valoriza a identidade de jogo ofensivo e de formação que fez o Ajax famoso. Cobra que o clube volte a ser competitivo na Champions League." },
  197: { name: "Toon Gerbrands", personality: "analitico", patience: 65, description: "CEO do PSV Eindhoven, gestão profissional com foco em data analytics. O PSV vive um dos melhores momentos recentes e as expectativas são altas. Tem paciência com projetos coerentes e valoriza a formação de jovens. Cobra que o PSV mantenha sua dominância na Eredivisie e avance na Europa League." },
  196: { name: "Dennis te Kloese", personality: "conservador", patience: 68, description: "CEO do Feyenoord Rotterdam, clube renascido com nova geração de talentos. Administra de forma profissional e valoriza o desenvolvimento sustentável. Tem paciência moderada e quer consolidar o Feyenoord entre os melhores clubes holandeses. A recente Eredivisie e a final da Conference League elevaram as expectativas do clube." },
  126: { name: "Maximiliano Romero", personality: "exigente", patience: 50, description: "Presidente do Club Atlético River Plate, um dos maiores clubes da América do Sul. Tem expectativas altíssimas e exige que o Millonario seja protagonista no futebol argentino e sul-americano. Não aceita temporadas sem títulos e cobra postura de clube grande em todos os jogos. A tradição e o tamanho do River demandam excelência constante." },
  112: { name: "Jorge Amor Ameal", personality: "diplomatico", patience: 58, description: "Presidente do Club Atlético Boca Juniors, dirigente histórico do clube xeneize. Vive intensamente a rivalidade com o River Plate e cobra que o Boca seja sempre protagonista. Tem paciência moderada e valoriza a identidade guerreira do clube. Entende que o Boca é o maior clube da Argentina e deve competir por todos os títulos." },
  623: { name: "Dursun Özbek", personality: "emocional", patience: 48, description: "Presidente do Galatasaray SK, um dos clubes mais apaixonantes da Turquia. Vive intensamente a rivalidade com Fenerbahçe e Beşiktaş. Não esconde suas emoções e pode ser impulsivo em momentos de derrota. Exige que o Galatasaray seja dominante na Süper Lig e competitive na Europa. A torcida turca é das mais intensas do mundo." },
  628: { name: "Ali Koç", personality: "agressivo", patience: 45, description: "Presidente do Fenerbahçe SK, empresário com grandes ambições para o clube amarelo-azul. Cobra forte da equipe e não aceita que o Fenerbahçe fique atrás do Galatasaray. Pode ser impulsivo e entra frequentemente em polêmicas com árbitros e rivais. Tem expectativas de trazer o Fenerbahçe de volta ao topo do futebol europeu." },
  617: { name: "Hasan Arat", personality: "exigente", patience: 50, description: "Presidente do Beşiktaş JK, clube histórico de Istambul. Exige comprometimento com a camisa preta e branca e cobra que o time seja competitivo. Tem paciência limitada com sequências ruins e pode tomar decisões rápidas quando os resultados frustram. Valoriza jogadores que entendam a grandeza histórica do clube." },
  631: { name: "İbrahim Hacıosmanoğlu", personality: "emocional", patience: 52, description: "Presidente do Trabzonspor, clube símbolo do Mar Negro turco. Apaixonado pelo clube e pela torcida bordo-mavi. Pode ser extremamente emocional e provocativo nas declarações públicas. Exige que o Trabzonspor seja competitivo e que represente com orgulho a Turquia nas competições europeias." },
  250: { name: "Peter Lawwell", personality: "analitico", patience: 68, description: "CEO do Celtic FC, clube histórico de Glasgow com identidade única. Administra com foco no equilíbrio financeiro e na competitividade nacional. Tem paciência com projetos coerentes que mantenham o Celtic dominante na Scottish Premiership. Cobra que o clube se qualifique regularmente para as fases de grupos da Champions League." },
  255: { name: "John Bennett", personality: "diplomatico", patience: 63, description: "Presidente do Rangers FC, clube histórico de Glasgow do lado protestante. Gere num momento de reconstrução e disputa intensa com o Celtic. Tem paciência com processos bem estruturados e valoriza o comprometimento com as cores azuis. Cobra que o Rangers seja competitivo e vença o Old Firm para conquistar o título escocês." },
};

const PATIENCE_BY_PERSONALITY: Record<string, number> = {
  conservador: 70,
  diplomatico: 68,
  analitico: 65,
  emocional: 52,
  exigente: 48,
  agressivo: 42,
};

const COUNTRY_NAMES: Record<string, string[]> = {
  Brazil: ["Carlos Eduardo Menezes", "Roberto Alves", "Fábio Rodrigues", "Marcelo Santos", "André Carvalho", "Paulo Henrique Costa", "Luiz Fernando Souza", "Thiago Barbosa"],
  England: ["Richard Thompson", "Michael Davies", "James Harrison", "Robert Clarke", "Andrew Wilson", "David Holloway", "Peter Ashworth", "Jonathan Blake"],
  Spain: ["Alejandro García", "Carlos Martínez", "Miguel Ángel López", "Francisco Romero", "Javier Sánchez", "Antonio Fernández", "Rafael Moreno", "Luis Castillo"],
  Italy: ["Luca Colombo", "Marco Rossi", "Giorgio Ferrari", "Alessandro Bruno", "Francesco Ricci", "Roberto Conti", "Stefano Palermo", "Davide Esposito"],
  Germany: ["Klaus Werner", "Jürgen Hoffmann", "Hans Schäfer", "Stefan Bauer", "Michael Koch", "Thomas Richter", "Andreas Schulz", "Markus Braun"],
  France: ["Jean-Pierre Moreau", "Philippe Lambert", "Michel Dupont", "François Martin", "Bernard Leroy", "Thierry Simon", "Alain Petit", "Christophe Girard"],
  Portugal: ["João Ferreira", "Rui Pinto", "Pedro Sousa", "Nuno Almeida", "Miguel Costa", "Luís Rodrigues", "António Silva", "Carlos Figueiredo"],
  Netherlands: ["Jan van der Berg", "Pieter Visser", "Willem de Groot", "Hendrik Bakker", "Johan Smit", "Dirk Muller", "Koen Jansen", "Bas van Dijk"],
  Argentina: ["Diego Rodríguez", "Martín González", "Pablo Álvarez", "Gustavo Pérez", "Hernán López", "Alejandro Silva", "Nicolás Castro", "Fabián Torres"],
  Mexico: ["Alejandro Torres", "Carlos Morales", "Roberto Gutiérrez", "Miguel Flores", "Juan Manuel Reyes", "Rodrigo Vargas", "Luis Medina", "Ernesto Pacheco"],
  Turkey: ["Ahmet Yilmaz", "Mehmet Demir", "Mustafa Kaya", "Ibrahim Celik", "Hasan Güler", "Ali Özdemir", "Emre Polat", "Osman Arslan"],
  Russia: ["Alexei Petrov", "Dmitri Volkov", "Igor Sokolov", "Nikolai Kuznetsov", "Sergei Morozov", "Vladimir Popov"],
  "United States": ["Robert Johnson", "Michael Davis", "James Anderson", "William Clarke", "Christopher Martin", "Matthew Harris", "Kevin Wilson"],
  China: ["Wei Zhang", "Jian Li", "Ming Wang", "Hao Chen", "Lei Liu", "Gang Zhao"],
  Japan: ["Hiroshi Tanaka", "Kenji Suzuki", "Yuki Yamamoto", "Takeshi Sato", "Makoto Watanabe", "Shinji Kimura"],
  Scotland: ["Alistair MacDonald", "Cameron Fraser", "Duncan McLean", "Iain Robertson", "Angus Campbell"],
  Belgium: ["Marc Devos", "Pierre Lebrun", "Thierry Claes", "Erik Janssen", "Luc Verbeke"],
  Colombia: ["Carlos Aristizabal", "Andrés Mejía", "Jorge Rendón", "Mauricio Pedraza", "Felipe Vargas"],
  Chile: ["Rodrigo Fuentes", "Pablo Herrera", "Sebastián Moya", "Cristóbal Lagos", "Felipe Sandoval"],
  Uruguay: ["Diego Fernández", "Pablo Méndez", "Andrés Suárez", "Rodrigo Pereyra", "Gustavo Giménez"],
  default: ["James Miller", "Carlos Oliveira", "Marco Ricci", "Pierre Dupont", "Heinrich Müller", "Alejandro Ruiz", "Ahmad Al-Hassan"],
};

const PERSONALITY_DESCRIPTIONS_PT: Record<string, string> = {
  conservador: "Presidente conservador e criterioso, prefere estabilidade ao risco. Dá suporte ao técnico enquanto vê progressão e cobra resultados consistentes. Gerencia o clube com prudência financeira e evita decisões impulsivas. Tem paciência com ciclos naturais do futebol, mas cobra comprometimento constante.",
  agressivo: "Presidente exigente e impaciente, espera resultados imediatos dos investimentos. Pode ser impulsivo em momentos de crise e pressiona o técnico constantemente. Tem dificuldade em aceitar sequências negativas e pode tomar decisões abruptas. No entanto, quando as coisas vão bem, celebra generosamente os resultados alcançados.",
  analitico: "Presidente analítico que toma decisões baseadas em dados e indicadores de desempenho. Avalia o trabalho do técnico com critério e objetividade. Dá suporte ao projeto enquanto os números justificam as escolhas táticas. Tem aversão a decisões impulsivas e valoriza planejamento de longo prazo.",
  emocional: "Presidente apaixonado que vive intensamente cada resultado da equipe. Pode ser impulsivo quando as coisas não vão bem, mas é extremamente generoso nos momentos de vitória. Valoriza conexão com os torcedores e espera que o técnico entenda a alma do clube. Tem sentimentos fortes sobre o estilo de jogo e a identidade da equipe.",
  diplomatico: "Presidente diplomático que navega bem entre torcida, jogadores e imprensa. Tem paciência com projetos de longo prazo e valoriza o comprometimento da equipe. Gere conflitos internos com habilidade e raramente entra em confronto público. Cobra resultados, mas entende que o futebol tem ciclos e dá tempo ao técnico para trabalhar.",
  exigente: "Presidente altamente exigente que não aceita mediocridade. Cobra alta performance em todas as competições e tem expectativas proporcionais ao potencial do clube. Analisa cada detalhe e questiona decisões táticas quando os resultados não satisfazem. Leal aos que entregam, mas implacável com quem decepciona.",
};

function getRandomItem<T>(arr: T[], seed: number): T {
  return arr[Math.abs(seed) % arr.length];
}

const PERSONALITIES: PersonalityStyle[] = ["conservador", "diplomatico", "analitico", "emocional", "exigente", "agressivo"];

export function getClubPresident(clubId: number): ClubPresidentData | null {
  return CLUB_PRESIDENTS[clubId] ?? null;
}

export function buildFallbackPresident(
  clubId: number,
  clubCountry?: string,
  personality?: string,
): ClubPresidentData {
  const personalityPool = PERSONALITIES;
  const pers = (personality as PersonalityStyle | undefined) ?? personalityPool[Math.abs(clubId) % personalityPool.length];
  const patience = PATIENCE_BY_PERSONALITY[pers] ?? 60;
  const countryNames = COUNTRY_NAMES[clubCountry ?? ""] ?? COUNTRY_NAMES.default;
  const name = getRandomItem(countryNames, clubId);
  const description = PERSONALITY_DESCRIPTIONS_PT[pers] ?? PERSONALITY_DESCRIPTIONS_PT.diplomatico;
  return { name, personality: pers, patience, description };
}
