export interface ClubColors {
  primary: string;
  secondary: string;
}

export interface ClubInfo extends ClubColors {
  league: string;
  sofifaId?: string;
}

export const CLUB_INFO: Record<string, ClubInfo> = {
  "Liverpool":        { primary: "#C8102E", secondary: "#00B2A9", league: "Premier League", sofifaId: "9" },
  "Real Madrid":      { primary: "#FEBE10", secondary: "#00529F", league: "LALIGA EA SPORTS", sofifaId: "243" },
  "Paris SG":         { primary: "#003370", secondary: "#DA291C", league: "Ligue 1 McDonald's", sofifaId: "73" },
  "Manchester City":  { primary: "#6CABDD", secondary: "#1C2C5B", league: "Premier League", sofifaId: "10" },
  "FC Barcelona":     { primary: "#A50044", secondary: "#004D98", league: "LALIGA EA SPORTS", sofifaId: "241" },
  "FC Bayern München":{ primary: "#DC052D", secondary: "#0066B2", league: "Bundesliga", sofifaId: "21" },
  "Arsenal":          { primary: "#EF0107", secondary: "#9C824A", league: "Premier League", sofifaId: "1" },
  "Atlético de Madrid":{ primary: "#CB3524", secondary: "#272E61", league: "LALIGA EA SPORTS", sofifaId: "240" },
  "Chelsea":          { primary: "#034694", secondary: "#DBA111", league: "Premier League", sofifaId: "5" },
  "Borussia Dortmund":{ primary: "#FDE100", secondary: "#000000", league: "Bundesliga", sofifaId: "22" },
  "SSC Napoli":       { primary: "#007AC2", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "48" },
  "Man Utd":          { primary: "#DA291C", secondary: "#000000", league: "Premier League", sofifaId: "11" },
  "Manchester Utd":   { primary: "#DA291C", secondary: "#000000", league: "Premier League", sofifaId: "11" },
  "Manchester United":{ primary: "#DA291C", secondary: "#000000", league: "Premier League", sofifaId: "11" },
  "Galatasaray":      { primary: "#CC0000", secondary: "#FFD700", league: "Trendyol Süper Lig", sofifaId: "174" },
  "AS Roma":          { primary: "#8B0000", secondary: "#FFD700", league: "Serie A Enilive", sofifaId: "42" },
  "Newcastle Utd":    { primary: "#000000", secondary: "#FFFFFF", league: "Premier League", sofifaId: "23" },
  "Athletic Club":    { primary: "#EE2523", secondary: "#FFFFFF", league: "LALIGA EA SPORTS", sofifaId: "237" },
  "Fenerbahçe":       { primary: "#FFD700", secondary: "#003087", league: "Trendyol Süper Lig", sofifaId: "178" },
  "Aston Villa":      { primary: "#95BFE5", secondary: "#670E36", league: "Premier League", sofifaId: "2" },
  "Al Ittihad":       { primary: "#000000", secondary: "#FFD700", league: "ROSHN Saudi League", sofifaId: "74" },
  "RB Leipzig":       { primary: "#DD0741", secondary: "#1B75BB", league: "Bundesliga", sofifaId: "114153" },
  "Fiorentina":       { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "68" },
  "Al Nassr":         { primary: "#FFD700", secondary: "#004B9D", league: "ROSHN Saudi League", sofifaId: "1772" },
  "Leverkusen":       { primary: "#E32221", secondary: "#000000", league: "Bundesliga", sofifaId: "25" },
  "Juventus":         { primary: "#000000", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "45" },
  "Al Hilal":         { primary: "#003DA5", secondary: "#FFFFFF", league: "ROSHN Saudi League", sofifaId: "1797" },
  "Everton":          { primary: "#003399", secondary: "#FFFFFF", league: "Premier League", sofifaId: "7" },
  "OM":               { primary: "#009AC7", secondary: "#FFFFFF", league: "Ligue 1 McDonald's", sofifaId: "76" },
  "Marseille":        { primary: "#009AC7", secondary: "#FFFFFF", league: "Ligue 1 McDonald's", sofifaId: "76" },
  "Olympique de Marseille":{ primary: "#009AC7", secondary: "#FFFFFF", league: "Ligue 1 McDonald's", sofifaId: "76" },
  "Latium":           { primary: "#87CEEB", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "47" },
  "Spurs":            { primary: "#132257", secondary: "#FFFFFF", league: "Premier League", sofifaId: "6" },
  "FC Porto":         { primary: "#003087", secondary: "#FFF200", league: "Liga Portugal", sofifaId: "229" },
  "Bergamo Calcio":   { primary: "#1C60A2", secondary: "#000000", league: "Serie A Enilive", sofifaId: "2687" },
  "Real Betis":       { primary: "#00A650", secondary: "#FFFFFF", league: "LALIGA EA SPORTS", sofifaId: "244" },
  "Al Ahli":          { primary: "#CC0000", secondary: "#FFFFFF", league: "ROSHN Saudi League", sofifaId: "112636" },
  "Sporting CP":      { primary: "#006600", secondary: "#FFFFFF", league: "Liga Portugal", sofifaId: "228" },
  "Sunderland":       { primary: "#CC0000", secondary: "#000000", league: "EFL Championship", sofifaId: "394" },
  "LAFC":             { primary: "#C39E6D", secondary: "#000000", league: "MLS", sofifaId: "112609" },
  "Inter Miami CF":   { primary: "#F7B5CD", secondary: "#000000", league: "MLS", sofifaId: "112625" },
  "Lombarida FC":     { primary: "#010E80", secondary: "#000000", league: "Serie A Enilive" },
  "Lombardia FC":     { primary: "#010E80", secondary: "#000000", league: "Serie A Enilive" },
  "Milano FC":        { primary: "#FB090B", secondary: "#000000", league: "Serie A Enilive" },
  "Ajax":             { primary: "#D2122E", secondary: "#FFFFFF", league: "Eredivisie", sofifaId: "139" },
  "Benfica":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Portugal", sofifaId: "1792" },
  "SL Benfica":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Portugal", sofifaId: "1792" },
  "Villarreal CF":    { primary: "#FFC900", secondary: "#004F9F", league: "LALIGA EA SPORTS", sofifaId: "449" },
  "Real Sociedad":    { primary: "#003DA5", secondary: "#FFFFFF", league: "LALIGA EA SPORTS", sofifaId: "1049" },
  "Sevilla FC":       { primary: "#D40000", secondary: "#FFFFFF", league: "LALIGA EA SPORTS", sofifaId: "481" },
  "Valencia CF":      { primary: "#F47920", secondary: "#000000", league: "LALIGA EA SPORTS", sofifaId: "1049" },
  "Celtic":           { primary: "#16A10C", secondary: "#FFFFFF", league: "Scottish Prem", sofifaId: "2566" },
  "Rangers":          { primary: "#003399", secondary: "#FFFFFF", league: "Scottish Prem", sofifaId: "543" },
  "Club Brugge":      { primary: "#003893", secondary: "#000000", league: "1A Pro League", sofifaId: "2282" },
  "Anderlecht":       { primary: "#6B2D8B", secondary: "#FFFFFF", league: "1A Pro League", sofifaId: "244" },
  "Olympique Lyonnais":{ primary: "#CC0000", secondary: "#002A5E", league: "Ligue 1 McDonald's", sofifaId: "80" },
  "AS Monaco":        { primary: "#E4001B", secondary: "#FFFFFF", league: "Ligue 1 McDonald's", sofifaId: "53" },
  "LOSC Lille":       { primary: "#DD0100", secondary: "#FFFFFF", league: "Ligue 1 McDonald's", sofifaId: "141" },
  "Eintracht Frankfurt":{ primary: "#E1001A", secondary: "#000000", league: "Bundesliga", sofifaId: "26" },
  "VfB Stuttgart":    { primary: "#E32219", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "32" },
  "Wolfsburg":        { primary: "#65B32E", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "27" },
  "Borussia M'gladbach":{ primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "29" },
  "Werder Bremen":    { primary: "#1D6B37", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "31" },
  "Flamengo":         { primary: "#CC0000", secondary: "#000000", league: "Libertadores" },
  "Palmeiras":        { primary: "#006B2B", secondary: "#FFFFFF", league: "Libertadores" },
  "Corinthians":      { primary: "#000000", secondary: "#FFFFFF", league: "Libertadores" },
  "Boca Juniors":     { primary: "#003087", secondary: "#FFF200", league: "Libertadores" },
  "River Plate":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Libertadores" },
  "Fluminense":       { primary: "#3F1F5E", secondary: "#CC0000", league: "Libertadores" },
  "Internacional":    { primary: "#C4001A", secondary: "#FFFFFF", league: "Libertadores" },
  "Grêmio":           { primary: "#009EE3", secondary: "#000000", league: "Libertadores" },
  "São Paulo":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Libertadores" },
  "Atlético Mineiro": { primary: "#000000", secondary: "#FFFFFF", league: "Libertadores" },
  "Santos":           { primary: "#000000", secondary: "#FFFFFF", league: "Libertadores" },
  "Peñarol":          { primary: "#FFC900", secondary: "#000000", league: "Sudamericana" },
  "Nacional":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Sudamericana" },
  "Club América":     { primary: "#FFD700", secondary: "#001a00", league: "Liga MX" },
  "Chivas":           { primary: "#CC0000", secondary: "#003DA5", league: "Liga MX" },
  "Cruz Azul":        { primary: "#1C60A2", secondary: "#FFFFFF", league: "Liga MX" },
  "LA Galaxy":        { primary: "#003087", secondary: "#FFD700", league: "MLS", sofifaId: "1068" },
  "Seattle Sounders": { primary: "#5D9B3F", secondary: "#003DA5", league: "MLS" },
  "Portland Timbers": { primary: "#004812", secondary: "#EBE72B", league: "MLS" },
  "Atlanta United":   { primary: "#80000A", secondary: "#FFFFFF", league: "MLS" },
  "New York City FC": { primary: "#6CABDD", secondary: "#003DA5", league: "MLS" },
  "West Ham Utd":     { primary: "#7A263A", secondary: "#1BB1E7", league: "Premier League", sofifaId: "37" },
  "Leicester City":   { primary: "#003090", secondary: "#FDBE11", league: "EFL Championship", sofifaId: "13" },
  "Wolves":           { primary: "#FDB913", secondary: "#231F20", league: "Premier League", sofifaId: "38" },
  "Brighton":         { primary: "#005DAA", secondary: "#FFFFFF", league: "Premier League", sofifaId: "405" },
  "Fulham":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Premier League", sofifaId: "50" },
  "Brentford":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Premier League", sofifaId: "101" },
  "Crystal Palace":   { primary: "#1B458F", secondary: "#A7A5A6", league: "Premier League", sofifaId: "8" },
  "Middlesbrough":    { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL Championship", sofifaId: "76" },
  "Leeds Utd":        { primary: "#FFFFFF", secondary: "#FFCD00", league: "EFL Championship", sofifaId: "110" },
  "Watford":          { primary: "#FBEE23", secondary: "#ED2127", league: "EFL Championship", sofifaId: "115" },
  "Burnley":          { primary: "#6C1D45", secondary: "#99D6EA", league: "EFL Championship", sofifaId: "19" },
  "Norwich City":     { primary: "#00A14E", secondary: "#FFF200", league: "EFL Championship", sofifaId: "58" },
  "Southampton":      { primary: "#D71920", secondary: "#130C0E", league: "EFL Championship", sofifaId: "17" },
  "Sheffield Utd":    { primary: "#EE2737", secondary: "#000000", league: "EFL Championship", sofifaId: "18" },
  "Luton Town":       { primary: "#F78F1E", secondary: "#002D62", league: "EFL Championship", sofifaId: "92" },
  "Ipswich Town":     { primary: "#0033A0", secondary: "#FFFFFF", league: "Premier League", sofifaId: "57" },
  "Nottm Forest":     { primary: "#DD0000", secondary: "#FFFFFF", league: "Premier League", sofifaId: "15" },
  "Bournemouth":      { primary: "#DA291C", secondary: "#000000", league: "Premier League", sofifaId: "127" },
  "Torino":           { primary: "#8B0000", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "46" },
  "Genoa":            { primary: "#AD1515", secondary: "#003DA5", league: "Serie A Enilive", sofifaId: "59" },
  "Bologna":          { primary: "#1A2857", secondary: "#A2001D", league: "Serie A Enilive", sofifaId: "52" },
  "Udinese":          { primary: "#000000", secondary: "#FFFFFF", league: "Serie A Enilive", sofifaId: "55" },
  "SC Freiburg":      { primary: "#E3000F", secondary: "#000000", league: "Bundesliga", sofifaId: "30" },
  "FC Augsburg":      { primary: "#BA3733", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "112114" },
  "1. FC Union Berlin":{ primary: "#EB1923", secondary: "#FFFFFF", league: "Bundesliga", sofifaId: "112172" },
  "Stade Rennais":    { primary: "#D4213C", secondary: "#000000", league: "Ligue 1 McDonald's", sofifaId: "97" },
  "RC Lens":          { primary: "#D4A843", secondary: "#CC0000", league: "Ligue 1 McDonald's", sofifaId: "116" },
  "Nice":             { primary: "#CC0000", secondary: "#000000", league: "Ligue 1 McDonald's", sofifaId: "83" },
  "Celta Vigo":       { primary: "#8AC3EE", secondary: "#CC0000", league: "LALIGA EA SPORTS", sofifaId: "455" },
  "RCD Mallorca":     { primary: "#CC0000", secondary: "#000000", league: "LALIGA EA SPORTS", sofifaId: "464" },
  "Girona FC":        { primary: "#CD2534", secondary: "#FFFFFF", league: "LALIGA EA SPORTS", sofifaId: "110770" },
  "Feyenoord":        { primary: "#EE1C25", secondary: "#FFFFFF", league: "Eredivisie", sofifaId: "142" },
  "PSV":              { primary: "#EE1C25", secondary: "#FFFFFF", league: "Eredivisie", sofifaId: "143" },
  "SC Braga":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Portugal", sofifaId: "234" },
  "Vasco":            { primary: "#000000", secondary: "#FFFFFF", league: "Libertadores" },
  "Botafogo":         { primary: "#000000", secondary: "#FFFFFF", league: "Libertadores" },
  "Cruzeiro":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Libertadores" },
  "Bahia":            { primary: "#003DA5", secondary: "#CC0000", league: "Libertadores" },
  "Fortaleza":        { primary: "#CC0000", secondary: "#003DA5", league: "Libertadores" },
  "Derby County":     { primary: "#000000", secondary: "#FFFFFF", league: "EFL Championship" },
  "Derby":            { primary: "#000000", secondary: "#FFFFFF", league: "EFL Championship" },
  "Barnsley":         { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Stoke City":       { primary: "#E03A3E", secondary: "#1B449C", league: "EFL Championship" },
  "Coventry City":    { primary: "#00A3E0", secondary: "#FFFFFF", league: "EFL Championship" },
  "Coventry":         { primary: "#00A3E0", secondary: "#FFFFFF", league: "EFL Championship" },
  "Blackburn Rovers": { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Blackburn":        { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Swansea City":     { primary: "#000000", secondary: "#FFFFFF", league: "EFL Championship" },
  "Swansea":          { primary: "#000000", secondary: "#FFFFFF", league: "EFL Championship" },
  "Bristol City":     { primary: "#E21836", secondary: "#FFFFFF", league: "EFL Championship" },
  "QPR":              { primary: "#005DAA", secondary: "#FFFFFF", league: "EFL Championship" },
  "Queens Park Rangers":{ primary: "#005DAA", secondary: "#FFFFFF", league: "EFL Championship" },
  "West Brom":        { primary: "#122F67", secondary: "#FFFFFF", league: "EFL Championship" },
  "West Bromwich Albion":{ primary: "#122F67", secondary: "#FFFFFF", league: "EFL Championship" },
  "Hull City":        { primary: "#F5A623", secondary: "#000000", league: "EFL Championship" },
  "Hull":             { primary: "#F5A623", secondary: "#000000", league: "EFL Championship" },
  "Preston North End":{ primary: "#FFFFFF", secondary: "#003087", league: "EFL Championship" },
  "Preston":          { primary: "#FFFFFF", secondary: "#003087", league: "EFL Championship" },
  "Plymouth Argyle":  { primary: "#00573F", secondary: "#FFFFFF", league: "EFL Championship" },
  "Plymouth":         { primary: "#00573F", secondary: "#FFFFFF", league: "EFL Championship" },
  "Cardiff City":     { primary: "#003DA5", secondary: "#D71920", league: "EFL Championship" },
  "Cardiff":          { primary: "#003DA5", secondary: "#D71920", league: "EFL Championship" },
  "Millwall":         { primary: "#003087", secondary: "#FFFFFF", league: "EFL Championship" },
  "Sheffield Wednesday":{ primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Sheffield Weds":   { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Portsmouth":       { primary: "#003DA5", secondary: "#D4AF37", league: "EFL Championship" },
  "Oxford United":    { primary: "#FFDD00", secondary: "#003087", league: "EFL Championship" },
  "Oxford Utd":       { primary: "#FFDD00", secondary: "#003087", league: "EFL Championship" },
  "Swindon Town":     { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Swindon":          { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Wigan Athletic":   { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Wigan":            { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Bolton Wanderers": { primary: "#003087", secondary: "#FFFFFF", league: "EFL League One" },
  "Bolton":           { primary: "#003087", secondary: "#FFFFFF", league: "EFL League One" },
  "Charlton Athletic":{ primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Charlton":         { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Reading":          { primary: "#004494", secondary: "#FFFFFF", league: "EFL League One" },
  "Blackpool":        { primary: "#F68B1F", secondary: "#FFFFFF", league: "EFL League One" },
  "Peterborough United":{ primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Peterborough":     { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Cambridge United": { primary: "#F5A623", secondary: "#000000", league: "EFL League One" },
  "Cambridge Utd":    { primary: "#F5A623", secondary: "#000000", league: "EFL League One" },
  "Huddersfield Town":{ primary: "#0073CF", secondary: "#FFFFFF", league: "EFL League One" },
  "Huddersfield":     { primary: "#0073CF", secondary: "#FFFFFF", league: "EFL League One" },
  "Birmingham City":  { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Birmingham":       { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL Championship" },
  "Wrexham":          { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Mansfield Town":   { primary: "#F5A623", secondary: "#003087", league: "EFL League Two" },
  "Mansfield":        { primary: "#F5A623", secondary: "#003087", league: "EFL League Two" },
  "Stockport County": { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Stockport":        { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League One" },
  "Doncaster Rovers": { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Doncaster":        { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Crewe Alexandra":  { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Crewe":            { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Notts County":     { primary: "#000000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Carlisle United":  { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Carlisle":         { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Grimsby Town":     { primary: "#000000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Grimsby":          { primary: "#000000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Bradford City":    { primary: "#7C2128", secondary: "#F5A623", league: "EFL League Two" },
  "Bradford":         { primary: "#7C2128", secondary: "#F5A623", league: "EFL League Two" },
  "MK Dons":          { primary: "#E21836", secondary: "#000000", league: "EFL League Two" },
  "Salford City":     { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Salford":          { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "AFC Wimbledon":    { primary: "#003DA5", secondary: "#FFDD00", league: "EFL League Two" },
  "Morecambe":        { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Harrogate Town":   { primary: "#FFD700", secondary: "#000000", league: "EFL League Two" },
  "Harrogate":        { primary: "#FFD700", secondary: "#000000", league: "EFL League Two" },
  "Accrington Stanley":{ primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Accrington":       { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Colchester United":{ primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Colchester":       { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Wycombe Wanderers":{ primary: "#003DA5", secondary: "#7BC6DD", league: "EFL League One" },
  "Wycombe":          { primary: "#003DA5", secondary: "#7BC6DD", league: "EFL League One" },
  "Exeter City":      { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Exeter":           { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Rotherham United": { primary: "#CC0000", secondary: "#FFD700", league: "EFL League One" },
  "Rotherham":        { primary: "#CC0000", secondary: "#FFD700", league: "EFL League One" },
  "Leyton Orient":    { primary: "#CC0000", secondary: "#000000", league: "EFL League One" },
  "Lincoln City":     { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Lincoln":          { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Northampton Town": { primary: "#7C2128", secondary: "#FFFFFF", league: "EFL League One" },
  "Northampton":      { primary: "#7C2128", secondary: "#FFFFFF", league: "EFL League One" },
  "Shrewsbury Town":  { primary: "#003DA5", secondary: "#FFD700", league: "EFL League One" },
  "Shrewsbury":       { primary: "#003DA5", secondary: "#FFD700", league: "EFL League One" },
  "Fleetwood Town":   { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Fleetwood":        { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League One" },
  "Burton Albion":    { primary: "#FFD700", secondary: "#000000", league: "EFL League One" },
  "Burton":           { primary: "#FFD700", secondary: "#000000", league: "EFL League One" },
  "Port Vale":        { primary: "#000000", secondary: "#FFD700", league: "EFL League Two" },
  "Crawley Town":     { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Crawley":          { primary: "#CC0000", secondary: "#FFFFFF", league: "EFL League Two" },
  "Newport County":   { primary: "#F5A623", secondary: "#000000", league: "EFL League Two" },
  "Newport":          { primary: "#F5A623", secondary: "#000000", league: "EFL League Two" },
  "Gillingham":       { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Tranmere Rovers":  { primary: "#FFFFFF", secondary: "#003DA5", league: "EFL League Two" },
  "Tranmere":         { primary: "#FFFFFF", secondary: "#003DA5", league: "EFL League Two" },
  "Barrow":           { primary: "#003DA5", secondary: "#FFFFFF", league: "EFL League Two" },
  "Sutton United":    { primary: "#F5A623", secondary: "#7C2128", league: "EFL League Two" },
  "Sutton":           { primary: "#F5A623", secondary: "#7C2128", league: "EFL League Two" },

  // === 2. Bundesliga ===
  "Hamburger SV":     { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "HSV":              { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "1. FC Köln":       { primary: "#E32221", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "FC Köln":          { primary: "#E32221", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Schalke 04":       { primary: "#004D9D", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "FC Schalke 04":    { primary: "#004D9D", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Hertha BSC":       { primary: "#005CA9", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Hertha Berlin":    { primary: "#005CA9", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Hannover 96":      { primary: "#009639", secondary: "#000000", league: "2. Bundesliga" },
  "Hannover":         { primary: "#009639", secondary: "#000000", league: "2. Bundesliga" },
  "1. FC Nürnberg":   { primary: "#8B0000", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Nürnberg":         { primary: "#8B0000", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Fortuna Düsseldorf":{ primary: "#E4002B", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "F. Düsseldorf":    { primary: "#E4002B", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "SC Paderborn 07":  { primary: "#005CA9", secondary: "#FFD700", league: "2. Bundesliga" },
  "Paderborn":        { primary: "#005CA9", secondary: "#FFD700", league: "2. Bundesliga" },
  "1. FC Kaiserslautern":{ primary: "#E4002B", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Kaiserslautern":   { primary: "#E4002B", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Karlsruher SC":    { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Karlsruhe":        { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "SV Darmstadt 98":  { primary: "#004D9D", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Darmstadt":        { primary: "#004D9D", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "SpVgg Greuther Fürth":{ primary: "#006B3F", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Greuther Fürth":   { primary: "#006B3F", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Dynamo Dresden":   { primary: "#FFD700", secondary: "#000000", league: "2. Bundesliga" },
  "SG Dynamo Dresden":{ primary: "#FFD700", secondary: "#000000", league: "2. Bundesliga" },
  "FC Magdeburg":     { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "1. FC Magdeburg":  { primary: "#003DA5", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Eintracht Braunschweig":{ primary: "#FFD700", secondary: "#003DA5", league: "2. Bundesliga" },
  "Braunschweig":     { primary: "#FFD700", secondary: "#003DA5", league: "2. Bundesliga" },
  "SV Elversberg":    { primary: "#003087", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Elversberg":       { primary: "#003087", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "SSV Ulm 1846":     { primary: "#000000", secondary: "#CC0000", league: "2. Bundesliga" },
  "Ulm":              { primary: "#000000", secondary: "#CC0000", league: "2. Bundesliga" },
  "Preußen Münster":  { primary: "#006B3F", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Münster":          { primary: "#006B3F", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Jahn Regensburg":  { primary: "#CC0000", secondary: "#FFFFFF", league: "2. Bundesliga" },
  "Regensburg":       { primary: "#CC0000", secondary: "#FFFFFF", league: "2. Bundesliga" },

  // === Ligue 1 (remaining) ===
  "RC Strasbourg":    { primary: "#003DA5", secondary: "#FFFFFF", league: "Ligue 1" },
  "Strasbourg":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Ligue 1" },
  "Stade de Reims":   { primary: "#CC0000", secondary: "#FFFFFF", league: "Ligue 1" },
  "Reims":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Ligue 1" },
  "Montpellier HSC":  { primary: "#003DA5", secondary: "#F47920", league: "Ligue 1" },
  "Montpellier":      { primary: "#003DA5", secondary: "#F47920", league: "Ligue 1" },
  "FC Nantes":        { primary: "#FFD700", secondary: "#006B3F", league: "Ligue 1" },
  "Nantes":           { primary: "#FFD700", secondary: "#006B3F", league: "Ligue 1" },
  "Toulouse FC":      { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Ligue 1" },
  "Toulouse":         { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Ligue 1" },
  "AJ Auxerre":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Ligue 1" },
  "Auxerre":          { primary: "#003DA5", secondary: "#FFFFFF", league: "Ligue 1" },
  "Angers SCO":       { primary: "#000000", secondary: "#FFFFFF", league: "Ligue 1" },
  "Angers":           { primary: "#000000", secondary: "#FFFFFF", league: "Ligue 1" },
  "AS Saint-Etienne": { primary: "#006B3F", secondary: "#FFFFFF", league: "Ligue 1" },
  "AS Saint-Étienne": { primary: "#006B3F", secondary: "#FFFFFF", league: "Ligue 1" },
  "Saint-Etienne":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Ligue 1" },
  "Le Havre AC":      { primary: "#009FE3", secondary: "#003DA5", league: "Ligue 1" },
  "Le Havre":         { primary: "#009FE3", secondary: "#003DA5", league: "Ligue 1" },
  "Stade Brestois 29":{ primary: "#CC0000", secondary: "#FFFFFF", league: "Ligue 1" },
  "Brest":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Ligue 1" },
  "Paris FC":         { primary: "#003087", secondary: "#FFFFFF", league: "Ligue 1" },

  // === Serie A (remaining) ===
  "Hellas Verona":    { primary: "#003DA5", secondary: "#FFD700", league: "Serie A" },
  "Verona":           { primary: "#003DA5", secondary: "#FFD700", league: "Serie A" },
  "Cagliari":         { primary: "#CC0000", secondary: "#003DA5", league: "Serie A" },
  "Empoli":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Serie A" },
  "US Lecce":         { primary: "#CC0000", secondary: "#FFD700", league: "Serie A" },
  "Lecce":            { primary: "#CC0000", secondary: "#FFD700", league: "Serie A" },
  "Venezia FC":       { primary: "#003D2C", secondary: "#F47920", league: "Serie A" },
  "Venezia":          { primary: "#003D2C", secondary: "#F47920", league: "Serie A" },
  "Como 1907":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Serie A" },
  "Como":             { primary: "#003DA5", secondary: "#FFFFFF", league: "Serie A" },
  "AC Monza":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Serie A" },
  "Monza":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Serie A" },
  "US Salernitana":   { primary: "#8B0000", secondary: "#FFD700", league: "Serie A" },
  "Salernitana":      { primary: "#8B0000", secondary: "#FFD700", league: "Serie A" },
  "Sassuolo":         { primary: "#006B3F", secondary: "#000000", league: "Serie A" },
  "Parma":            { primary: "#003DA5", secondary: "#FFD700", league: "Serie A" },
  "Parma Calcio 1913":{ primary: "#003DA5", secondary: "#FFD700", league: "Serie A" },
  "Frosinone":        { primary: "#FFD700", secondary: "#003DA5", league: "Serie A" },
  "Sampdoria":        { primary: "#003DA5", secondary: "#CC0000", league: "Serie A" },
  "Palermo":          { primary: "#F72585", secondary: "#000000", league: "Serie B" },
  "Brescia":          { primary: "#003DA5", secondary: "#FFFFFF", league: "Serie B" },
  "Bari":             { primary: "#CC0000", secondary: "#FFFFFF", league: "Serie B" },
  "Spezia":           { primary: "#000000", secondary: "#FFFFFF", league: "Serie B" },
  "Cremonese":        { primary: "#CC0000", secondary: "#808080", league: "Serie B" },
  "Catanzaro":        { primary: "#FFD700", secondary: "#CC0000", league: "Serie B" },
  "Modena":           { primary: "#FFD700", secondary: "#003DA5", league: "Serie B" },
  "Pisa":             { primary: "#003DA5", secondary: "#000000", league: "Serie B" },
  "Reggiana":         { primary: "#8B0000", secondary: "#FFFFFF", league: "Serie B" },

  // === LaLiga (remaining) ===
  "Deportivo Alavés": { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Alavés":           { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "CA Osasuna":       { primary: "#CC0000", secondary: "#003087", league: "LaLiga" },
  "Osasuna":          { primary: "#CC0000", secondary: "#003087", league: "LaLiga" },
  "Getafe CF":        { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Getafe":           { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Rayo Vallecano":   { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga" },
  "Rayo":             { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga" },
  "UD Las Palmas":    { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga" },
  "Las Palmas":       { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga" },
  "Cádiz CF":         { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga" },
  "Cádiz":            { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga" },
  "RC Celta":         { primary: "#8AC3EE", secondary: "#CC0000", league: "LaLiga" },
  "Real Valladolid":  { primary: "#6B2FA0", secondary: "#FFFFFF", league: "LaLiga" },
  "Valladolid":       { primary: "#6B2FA0", secondary: "#FFFFFF", league: "LaLiga" },
  "RCD Espanyol":     { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Espanyol":         { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "CD Leganés":       { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Leganés":          { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga" },
  "Real Zaragoza":    { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Zaragoza":         { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Sporting Gijón":   { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Levante UD":       { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Levante":          { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "SD Eibar":         { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Eibar":            { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Racing Santander": { primary: "#006B3F", secondary: "#FFFFFF", league: "LaLiga 2" },
  "SD Huesca":        { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Huesca":           { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Tenerife":         { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Albacete":         { primary: "#FFFFFF", secondary: "#CC0000", league: "LaLiga 2" },
  "Albacete BP":      { primary: "#FFFFFF", secondary: "#CC0000", league: "LaLiga 2" },
  "CD Tenerife":      { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "UD Almería":       { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Almería":          { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Burgos CF":        { primary: "#000000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Burgos":           { primary: "#000000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "CD Eldense":       { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Eldense":          { primary: "#003DA5", secondary: "#CC0000", league: "LaLiga 2" },
  "Elche CF":         { primary: "#006B3F", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Elche":            { primary: "#006B3F", secondary: "#FFFFFF", league: "LaLiga 2" },
  "FC Andorra":       { primary: "#FFD700", secondary: "#CC0000", league: "LaLiga 2" },
  "Andorra":          { primary: "#FFD700", secondary: "#CC0000", league: "LaLiga 2" },
  "CD Mirandés":      { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Mirandés":         { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Real Oviedo":      { primary: "#003DA5", secondary: "#000000", league: "LaLiga 2" },
  "Oviedo":           { primary: "#003DA5", secondary: "#000000", league: "LaLiga 2" },
  "CD Castellón":     { primary: "#000000", secondary: "#FFD700", league: "LaLiga 2" },
  "Castellón":        { primary: "#000000", secondary: "#FFD700", league: "LaLiga 2" },
  "RC Deportivo":     { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Deportivo":        { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Deportivo de La Coruña": { primary: "#003DA5", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Racing Ferrol":    { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Racing Club Ferrol": { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },
  "Córdoba CF":       { primary: "#FFFFFF", secondary: "#006B3F", league: "LaLiga 2" },
  "Córdoba":          { primary: "#FFFFFF", secondary: "#006B3F", league: "LaLiga 2" },
  "Villarreal B":     { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga 2" },
  "Villarreal CF B":  { primary: "#FFD700", secondary: "#003DA5", league: "LaLiga 2" },
  "Nástic":           { primary: "#CC0000", secondary: "#FFD700", league: "LaLiga 2" },
  "Nàstic":           { primary: "#CC0000", secondary: "#FFD700", league: "LaLiga 2" },
  "Gimnàstic":        { primary: "#CC0000", secondary: "#FFD700", league: "LaLiga 2" },
  "Gimnàstic de Tarragona": { primary: "#CC0000", secondary: "#FFD700", league: "LaLiga 2" },
  "FC Cartagena":     { primary: "#CC0000", secondary: "#003DA5", league: "LaLiga 2" },
  "Cartagena":        { primary: "#CC0000", secondary: "#003DA5", league: "LaLiga 2" },
  "Almeria":          { primary: "#CC0000", secondary: "#FFFFFF", league: "LaLiga 2" },

  // === Eredivisie (remaining) ===
  "AZ Alkmaar":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "AZ":               { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "FC Twente":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "Twente":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "FC Utrecht":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "Utrecht":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "Vitesse":          { primary: "#FFD700", secondary: "#000000", league: "Eredivisie" },
  "SC Heerenveen":    { primary: "#003DA5", secondary: "#FFFFFF", league: "Eredivisie" },
  "Heerenveen":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Eredivisie" },
  "FC Groningen":     { primary: "#006B3F", secondary: "#FFFFFF", league: "Eredivisie" },
  "Groningen":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Eredivisie" },
  "Sparta Rotterdam": { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "Sparta":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Eredivisie" },
  "NEC Nijmegen":     { primary: "#CC0000", secondary: "#006B3F", league: "Eredivisie" },
  "NEC":              { primary: "#CC0000", secondary: "#006B3F", league: "Eredivisie" },
  "Go Ahead Eagles":  { primary: "#CC0000", secondary: "#FFD700", league: "Eredivisie" },
  "Willem II":        { primary: "#CC0000", secondary: "#003DA5", league: "Eredivisie" },
  "Heracles Almelo":  { primary: "#000000", secondary: "#FFFFFF", league: "Eredivisie" },
  "Heracles":         { primary: "#000000", secondary: "#FFFFFF", league: "Eredivisie" },
  "RKC Waalwijk":     { primary: "#FFD700", secondary: "#003DA5", league: "Eredivisie" },
  "RKC":              { primary: "#FFD700", secondary: "#003DA5", league: "Eredivisie" },
  "Fortuna Sittard":  { primary: "#FFD700", secondary: "#006B3F", league: "Eredivisie" },
  "PEC Zwolle":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Eredivisie" },
  "Almere City FC":   { primary: "#CC0000", secondary: "#000000", league: "Eredivisie" },
  "Almere City":      { primary: "#CC0000", secondary: "#000000", league: "Eredivisie" },
  "NAC Breda":        { primary: "#FFD700", secondary: "#CC0000", league: "Eredivisie" },
  "NAC":              { primary: "#FFD700", secondary: "#CC0000", league: "Eredivisie" },

  // === Liga Portugal (remaining) ===
  "Vitória SC":       { primary: "#FFFFFF", secondary: "#006B3F", league: "Liga Portugal" },
  "Vitória de Guimarães":{ primary: "#FFFFFF", secondary: "#006B3F", league: "Liga Portugal" },
  "Guimarães":        { primary: "#FFFFFF", secondary: "#006B3F", league: "Liga Portugal" },
  "Boavista FC":      { primary: "#000000", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Boavista":         { primary: "#000000", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Gil Vicente":      { primary: "#CC0000", secondary: "#003DA5", league: "Liga Portugal" },
  "Moreirense":       { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Famalicão":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "FC Famalicão":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Rio Ave":          { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Rio Ave FC":       { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Casa Pia AC":      { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Casa Pia":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Estoril Praia":    { primary: "#FFD700", secondary: "#003DA5", league: "Liga Portugal" },
  "Estoril":          { primary: "#FFD700", secondary: "#003DA5", league: "Liga Portugal" },
  "Arouca":           { primary: "#FFD700", secondary: "#000000", league: "Liga Portugal" },
  "FC Arouca":        { primary: "#FFD700", secondary: "#000000", league: "Liga Portugal" },
  "CD Nacional":      { primary: "#000000", secondary: "#CC0000", league: "Liga Portugal" },
  "Estrela Amadora":  { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Portugal" },
  "AVS":              { primary: "#CC0000", secondary: "#000000", league: "Liga Portugal" },
  "FC Vizela":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Vizela":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Portugal" },
  "Santa Clara":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Portugal" },

  // === Belgian Pro League (remaining) ===
  "KRC Genk":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Pro League" },
  "Genk":             { primary: "#003DA5", secondary: "#FFFFFF", league: "Pro League" },
  "Standard Liège":   { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Standard Liege":   { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Standard de Liège":{ primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "KAA Gent":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Pro League" },
  "Gent":             { primary: "#003DA5", secondary: "#FFFFFF", league: "Pro League" },
  "Royal Antwerp FC": { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Antwerp":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Union Saint-Gilloise":{ primary: "#FFD700", secondary: "#003DA5", league: "Pro League" },
  "Union SG":         { primary: "#FFD700", secondary: "#003DA5", league: "Pro League" },
  "Cercle Brugge":    { primary: "#006B3F", secondary: "#000000", league: "Pro League" },
  "KV Mechelen":      { primary: "#FFD700", secondary: "#CC0000", league: "Pro League" },
  "Mechelen":         { primary: "#FFD700", secondary: "#CC0000", league: "Pro League" },
  "OH Leuven":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Pro League" },
  "Leuven":           { primary: "#006B3F", secondary: "#FFFFFF", league: "Pro League" },
  "Charleroi":        { primary: "#000000", secondary: "#FFFFFF", league: "Pro League" },
  "Sporting Charleroi":{ primary: "#000000", secondary: "#FFFFFF", league: "Pro League" },
  "Sint-Truiden":     { primary: "#FFD700", secondary: "#003DA5", league: "Pro League" },
  "STVV":             { primary: "#FFD700", secondary: "#003DA5", league: "Pro League" },
  "Westerlo":         { primary: "#003DA5", secondary: "#FFD700", league: "Pro League" },
  "KV Kortrijk":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Kortrijk":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Pro League" },
  "Eupen":            { primary: "#000000", secondary: "#FFFFFF", league: "Pro League" },

  // === Scottish Premiership (remaining) ===
  "Aberdeen":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Heart of Midlothian":{ primary: "#7C2128", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Hearts":           { primary: "#7C2128", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Hibernian":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Hibs":             { primary: "#006B3F", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Dundee United":    { primary: "#F47920", secondary: "#000000", league: "Scottish Prem" },
  "Dundee FC":        { primary: "#003087", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Dundee":           { primary: "#003087", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Motherwell":       { primary: "#7C2128", secondary: "#FFD700", league: "Scottish Prem" },
  "St Mirren":        { primary: "#000000", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Kilmarnock":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Ross County":      { primary: "#003087", secondary: "#CC0000", league: "Scottish Prem" },
  "St Johnstone":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Scottish Prem" },
  "Livingston":       { primary: "#FFD700", secondary: "#000000", league: "Scottish Prem" },

  // === Turkish Süper Lig (remaining) ===
  "Beşiktaş":         { primary: "#000000", secondary: "#FFFFFF", league: "Süper Lig" },
  "Besiktas":         { primary: "#000000", secondary: "#FFFFFF", league: "Süper Lig" },
  "Trabzonspor":      { primary: "#7C2128", secondary: "#009FE3", league: "Süper Lig" },
  "İstanbul Başakşehir":{ primary: "#F47920", secondary: "#003DA5", league: "Süper Lig" },
  "Istanbul Basaksehir":{ primary: "#F47920", secondary: "#003DA5", league: "Süper Lig" },
  "Adana Demirspor":  { primary: "#003DA5", secondary: "#F47920", league: "Süper Lig" },
  "Antalyaspor":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Süper Lig" },
  "Sivasspor":        { primary: "#CC0000", secondary: "#003DA5", league: "Süper Lig" },
  "Kasimpasa":        { primary: "#003DA5", secondary: "#FFD700", league: "Süper Lig" },
  "Konyaspor":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Süper Lig" },
  "Alanyaspor":       { primary: "#F47920", secondary: "#006B3F", league: "Süper Lig" },
  "Gaziantep FK":     { primary: "#CC0000", secondary: "#000000", league: "Süper Lig" },
  "Rizespor":         { primary: "#006B3F", secondary: "#003DA5", league: "Süper Lig" },
  "Kayserispor":      { primary: "#FFD700", secondary: "#CC0000", league: "Süper Lig" },
  "Hatayspor":        { primary: "#CC0000", secondary: "#FFD700", league: "Süper Lig" },
  "Pendikspor":       { primary: "#CC0000", secondary: "#003DA5", league: "Süper Lig" },
  "Samsunspor":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Süper Lig" },
  "Eyüpspor":         { primary: "#CC0000", secondary: "#FFD700", league: "Süper Lig" },
  "Bodrum FK":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Süper Lig" },

  // === Saudi Pro League (remaining) ===
  "Al Shabab":        { primary: "#FFFFFF", secondary: "#000000", league: "Saudi Pro League" },
  "Al Fateh":         { primary: "#006B3F", secondary: "#FFFFFF", league: "Saudi Pro League" },
  "Al Taawoun":       { primary: "#FFD700", secondary: "#003DA5", league: "Saudi Pro League" },
  "Al Raed":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Saudi Pro League" },
  "Al Feiha":         { primary: "#FFD700", secondary: "#006B3F", league: "Saudi Pro League" },
  "Al Ettifaq":       { primary: "#006B3F", secondary: "#FFFFFF", league: "Saudi Pro League" },
  "Al Khaleej":       { primary: "#F47920", secondary: "#003DA5", league: "Saudi Pro League" },
  "Al Wehda":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Saudi Pro League" },
  "Al Okhdood":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Saudi Pro League" },
  "Damac FC":         { primary: "#6B2FA0", secondary: "#FFD700", league: "Saudi Pro League" },
  "Damac":            { primary: "#6B2FA0", secondary: "#FFD700", league: "Saudi Pro League" },
  "Abha Club":        { primary: "#CC0000", secondary: "#FFD700", league: "Saudi Pro League" },
  "Abha":             { primary: "#CC0000", secondary: "#FFD700", league: "Saudi Pro League" },
  "Al Hazem":         { primary: "#FFD700", secondary: "#CC0000", league: "Saudi Pro League" },

  // === Argentine Liga Profesional ===
  "Racing Club":      { primary: "#009FE3", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Racing":           { primary: "#009FE3", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Independiente":    { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "San Lorenzo":      { primary: "#003DA5", secondary: "#CC0000", league: "Liga Profesional" },
  "Vélez Sarsfield":  { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Vélez":            { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Rosario Central":  { primary: "#003DA5", secondary: "#FFD700", league: "Liga Profesional" },
  "Newell's Old Boys":{ primary: "#CC0000", secondary: "#000000", league: "Liga Profesional" },
  "Estudiantes":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Estudiantes LP":   { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Lanús":            { primary: "#8B0000", secondary: "#FFD700", league: "Liga Profesional" },
  "Lanus":            { primary: "#8B0000", secondary: "#FFD700", league: "Liga Profesional" },
  "Talleres":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Talleres Córdoba": { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Defensa y Justicia":{ primary: "#FFD700", secondary: "#006B3F", league: "Liga Profesional" },
  "Banfield":         { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Argentinos Juniors":{ primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Belgrano":         { primary: "#009FE3", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Godoy Cruz":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Tigre":            { primary: "#003DA5", secondary: "#CC0000", league: "Liga Profesional" },
  "Colón":            { primary: "#CC0000", secondary: "#000000", league: "Liga Profesional" },
  "Unión":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Union Santa Fe":   { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Central Córdoba":  { primary: "#000000", secondary: "#FFD700", league: "Liga Profesional" },
  "Huracán":          { primary: "#FFFFFF", secondary: "#CC0000", league: "Liga Profesional" },
  "Huracan":          { primary: "#FFFFFF", secondary: "#CC0000", league: "Liga Profesional" },
  "Platense":         { primary: "#7C2128", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Barracas Central": { primary: "#CC0000", secondary: "#003DA5", league: "Liga Profesional" },
  "Gimnasia LP":      { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Gimnasia":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Sarmiento":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga Profesional" },
  "Instituto":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga Profesional" },

  // === MLS (remaining) ===
  "New York Red Bulls":{ primary: "#CC0000", secondary: "#003087", league: "MLS" },
  "NY Red Bulls":     { primary: "#CC0000", secondary: "#003087", league: "MLS" },
  "Columbus Crew":    { primary: "#FFD700", secondary: "#000000", league: "MLS" },
  "Toronto FC":       { primary: "#CC0000", secondary: "#A0A0A0", league: "MLS" },
  "CF Montréal":      { primary: "#003DA5", secondary: "#000000", league: "MLS" },
  "Montreal":         { primary: "#003DA5", secondary: "#000000", league: "MLS" },
  "Philadelphia Union":{ primary: "#003DA5", secondary: "#FFD700", league: "MLS" },
  "D.C. United":      { primary: "#CC0000", secondary: "#000000", league: "MLS" },
  "DC United":        { primary: "#CC0000", secondary: "#000000", league: "MLS" },
  "Chicago Fire":     { primary: "#CC0000", secondary: "#003DA5", league: "MLS" },
  "Nashville SC":     { primary: "#FFD700", secondary: "#003087", league: "MLS" },
  "Charlotte FC":     { primary: "#003DA5", secondary: "#009FE3", league: "MLS" },
  "Austin FC":        { primary: "#006B3F", secondary: "#000000", league: "MLS" },
  "Houston Dynamo":   { primary: "#F47920", secondary: "#FFFFFF", league: "MLS" },
  "FC Dallas":        { primary: "#CC0000", secondary: "#003DA5", league: "MLS" },
  "Colorado Rapids":  { primary: "#7C2128", secondary: "#009FE3", league: "MLS" },
  "Real Salt Lake":   { primary: "#CC0000", secondary: "#003DA5", league: "MLS" },
  "Sporting KC":      { primary: "#003DA5", secondary: "#9BCBEB", league: "MLS" },
  "Minnesota United": { primary: "#9BCBEB", secondary: "#003087", league: "MLS" },
  "San Jose Earthquakes":{ primary: "#003DA5", secondary: "#000000", league: "MLS" },
  "San Jose":         { primary: "#003DA5", secondary: "#000000", league: "MLS" },
  "Vancouver Whitecaps":{ primary: "#003DA5", secondary: "#FFFFFF", league: "MLS" },
  "Orlando City":     { primary: "#6B2FA0", secondary: "#FFD700", league: "MLS" },
  "St. Louis City SC":{ primary: "#CC0000", secondary: "#003087", league: "MLS" },
  "St. Louis":        { primary: "#CC0000", secondary: "#003087", league: "MLS" },
  "FC Cincinnati":    { primary: "#003DA5", secondary: "#F47920", league: "MLS" },
  "Cincinnati":       { primary: "#003DA5", secondary: "#F47920", league: "MLS" },

  // === Swiss Super League ===
  "BSC Young Boys":   { primary: "#FFD700", secondary: "#000000", league: "Super League" },
  "Young Boys":       { primary: "#FFD700", secondary: "#000000", league: "Super League" },
  "FC Basel":         { primary: "#CC0000", secondary: "#003DA5", league: "Super League" },
  "Basel":            { primary: "#CC0000", secondary: "#003DA5", league: "Super League" },
  "FC Zürich":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "Zürich":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "Grasshopper Club": { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "Grasshoppers":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "FC Lugano":        { primary: "#000000", secondary: "#FFFFFF", league: "Super League" },
  "Lugano":           { primary: "#000000", secondary: "#FFFFFF", league: "Super League" },
  "FC Luzern":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "Luzern":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Super League" },
  "Servette FC":      { primary: "#8B0000", secondary: "#FFFFFF", league: "Super League" },
  "Servette":         { primary: "#8B0000", secondary: "#FFFFFF", league: "Super League" },
  "FC St. Gallen":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Super League" },
  "St. Gallen":       { primary: "#006B3F", secondary: "#FFFFFF", league: "Super League" },
  "FC Sion":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Super League" },
  "Sion":             { primary: "#CC0000", secondary: "#FFFFFF", league: "Super League" },
  "FC Winterthur":    { primary: "#CC0000", secondary: "#FFFFFF", league: "Super League" },
  "Winterthur":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Super League" },
  "Yverdon Sport":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Super League" },
  "Yverdon":          { primary: "#006B3F", secondary: "#FFFFFF", league: "Super League" },

  // === Austrian Bundesliga ===
  "RB Salzburg":      { primary: "#CC0000", secondary: "#FFD700", league: "Bundesliga AT" },
  "Red Bull Salzburg":{ primary: "#CC0000", secondary: "#FFD700", league: "Bundesliga AT" },
  "SK Sturm Graz":    { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Sturm Graz":       { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "SK Rapid Wien":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Rapid Wien":       { primary: "#006B3F", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "FK Austria Wien":  { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Austria Wien":     { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "LASK":             { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "LASK Linz":        { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Wolfsberger AC":   { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Wolfsberg":        { primary: "#000000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "TSV Hartberg":     { primary: "#003DA5", secondary: "#FFD700", league: "Bundesliga AT" },
  "Hartberg":         { primary: "#003DA5", secondary: "#FFD700", league: "Bundesliga AT" },
  "SCR Altach":       { primary: "#000000", secondary: "#CC0000", league: "Bundesliga AT" },
  "Altach":           { primary: "#000000", secondary: "#CC0000", league: "Bundesliga AT" },
  "Austria Klagenfurt":{ primary: "#6B2FA0", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "WSG Tirol":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Tirol":            { primary: "#006B3F", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "SV Ried":          { primary: "#006B3F", secondary: "#000000", league: "Bundesliga AT" },
  "Ried":             { primary: "#006B3F", secondary: "#000000", league: "Bundesliga AT" },
  "Austria Lustenau": { primary: "#006B3F", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Blau-Weiß Linz":  { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "BW Linz":          { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "Grazer AK":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Bundesliga AT" },
  "GAK":              { primary: "#CC0000", secondary: "#FFFFFF", league: "Bundesliga AT" },

  // === Polish Ekstraklasa ===
  "Legia Warszawa":   { primary: "#006B3F", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Legia Warsaw":     { primary: "#006B3F", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Legia":            { primary: "#006B3F", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Lech Poznań":      { primary: "#003DA5", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Lech Poznan":      { primary: "#003DA5", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Raków Częstochowa":{ primary: "#CC0000", secondary: "#003DA5", league: "Ekstraklasa" },
  "Raków":            { primary: "#CC0000", secondary: "#003DA5", league: "Ekstraklasa" },
  "Jagiellonia Białystok":{ primary: "#FFD700", secondary: "#CC0000", league: "Ekstraklasa" },
  "Jagiellonia":      { primary: "#FFD700", secondary: "#CC0000", league: "Ekstraklasa" },
  "Pogoń Szczecin":   { primary: "#003DA5", secondary: "#7C2128", league: "Ekstraklasa" },
  "Pogoń":            { primary: "#003DA5", secondary: "#7C2128", league: "Ekstraklasa" },
  "Piast Gliwice":    { primary: "#003DA5", secondary: "#CC0000", league: "Ekstraklasa" },
  "Wisła Kraków":     { primary: "#CC0000", secondary: "#003DA5", league: "Ekstraklasa" },
  "Wisła":            { primary: "#CC0000", secondary: "#003DA5", league: "Ekstraklasa" },
  "Cracovia":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Śląsk Wrocław":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Górnik Zabrze":    { primary: "#003DA5", secondary: "#CC0000", league: "Ekstraklasa" },
  "Zagłębie Lubin":   { primary: "#F47920", secondary: "#003DA5", league: "Ekstraklasa" },
  "Warta Poznań":     { primary: "#006B3F", secondary: "#FFD700", league: "Ekstraklasa" },
  "Korona Kielce":    { primary: "#FFD700", secondary: "#CC0000", league: "Ekstraklasa" },
  "Stal Mielec":      { primary: "#003DA5", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Widzew Łódź":      { primary: "#CC0000", secondary: "#FFFFFF", league: "Ekstraklasa" },
  "Widzew":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Ekstraklasa" },

  // === Scandinavian leagues ===
  "Malmö FF":         { primary: "#009FE3", secondary: "#FFFFFF", league: "Allsvenskan" },
  "Malmö":            { primary: "#009FE3", secondary: "#FFFFFF", league: "Allsvenskan" },
  "AIK":              { primary: "#000000", secondary: "#FFD700", league: "Allsvenskan" },
  "Djurgårdens IF":   { primary: "#003DA5", secondary: "#CC0000", league: "Allsvenskan" },
  "Djurgården":       { primary: "#003DA5", secondary: "#CC0000", league: "Allsvenskan" },
  "IF Elfsborg":      { primary: "#FFD700", secondary: "#000000", league: "Allsvenskan" },
  "Elfsborg":         { primary: "#FFD700", secondary: "#000000", league: "Allsvenskan" },
  "Hammarby IF":      { primary: "#006B3F", secondary: "#FFFFFF", league: "Allsvenskan" },
  "Hammarby":         { primary: "#006B3F", secondary: "#FFFFFF", league: "Allsvenskan" },
  "IFK Göteborg":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Allsvenskan" },
  "IFK Norrköping":   { primary: "#003DA5", secondary: "#FFFFFF", league: "Allsvenskan" },
  "BK Häcken":        { primary: "#FFD700", secondary: "#000000", league: "Allsvenskan" },
  "Häcken":           { primary: "#FFD700", secondary: "#000000", league: "Allsvenskan" },
  "Kalmar FF":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Allsvenskan" },
  "Kalmar":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Allsvenskan" },
  "Bodø/Glimt":       { primary: "#FFD700", secondary: "#000000", league: "Eliteserien" },
  "Bodø Glimt":       { primary: "#FFD700", secondary: "#000000", league: "Eliteserien" },
  "Rosenborg":        { primary: "#000000", secondary: "#FFFFFF", league: "Eliteserien" },
  "Molde FK":         { primary: "#003DA5", secondary: "#FFFFFF", league: "Eliteserien" },
  "Molde":            { primary: "#003DA5", secondary: "#FFFFFF", league: "Eliteserien" },
  "Viking FK":        { primary: "#003087", secondary: "#FFFFFF", league: "Eliteserien" },
  "Viking":           { primary: "#003087", secondary: "#FFFFFF", league: "Eliteserien" },
  "Brann":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Eliteserien" },
  "SK Brann":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Eliteserien" },
  "Lillestrøm":       { primary: "#FFD700", secondary: "#000000", league: "Eliteserien" },
  "Vålerenga":        { primary: "#003DA5", secondary: "#CC0000", league: "Eliteserien" },
  "FC København":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "Copenhagen":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "FC Midtjylland":   { primary: "#CC0000", secondary: "#000000", league: "Superliga DK" },
  "Midtjylland":      { primary: "#CC0000", secondary: "#000000", league: "Superliga DK" },
  "Brøndby IF":       { primary: "#FFD700", secondary: "#003DA5", league: "Superliga DK" },
  "Brøndby":          { primary: "#FFD700", secondary: "#003DA5", league: "Superliga DK" },
  "FC Nordsjælland":  { primary: "#CC0000", secondary: "#FFD700", league: "Superliga DK" },
  "Nordsjælland":     { primary: "#CC0000", secondary: "#FFD700", league: "Superliga DK" },
  "AGF Aarhus":       { primary: "#FFFFFF", secondary: "#003DA5", league: "Superliga DK" },
  "AGF":              { primary: "#FFFFFF", secondary: "#003DA5", league: "Superliga DK" },
  "Randers FC":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "Silkeborg IF":     { primary: "#CC0000", secondary: "#FFFFFF", league: "Superliga DK" },
  "Silkeborg":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Superliga DK" },
  "Viborg FF":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Superliga DK" },
  "Viborg":           { primary: "#006B3F", secondary: "#FFFFFF", league: "Superliga DK" },
  "OB":               { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "Odense":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "AaB":              { primary: "#CC0000", secondary: "#FFFFFF", league: "Superliga DK" },
  "Aalborg":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Superliga DK" },
  "Lyngby BK":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },
  "Lyngby":            { primary: "#003DA5", secondary: "#FFFFFF", league: "Superliga DK" },

  // === K League / J League / A-League / Chinese Super League ===
  "Jeonbuk Hyundai":  { primary: "#006B3F", secondary: "#FFFFFF", league: "K League 1" },
  "Jeonbuk":          { primary: "#006B3F", secondary: "#FFFFFF", league: "K League 1" },
  "Ulsan HD":         { primary: "#003DA5", secondary: "#F47920", league: "K League 1" },
  "Ulsan Hyundai":    { primary: "#003DA5", secondary: "#F47920", league: "K League 1" },
  "FC Seoul":         { primary: "#CC0000", secondary: "#000000", league: "K League 1" },
  "Suwon Samsung":    { primary: "#003DA5", secondary: "#CC0000", league: "K League 1" },
  "Pohang Steelers":  { primary: "#CC0000", secondary: "#000000", league: "K League 1" },
  "Daegu FC":         { primary: "#003DA5", secondary: "#CC0000", league: "K League 1" },
  "Incheon United":   { primary: "#003DA5", secondary: "#FFFFFF", league: "K League 1" },
  "Gwangju FC":       { primary: "#FFD700", secondary: "#006B3F", league: "K League 1" },
  "Jeju United":      { primary: "#F47920", secondary: "#000000", league: "K League 1" },
  "Gangwon FC":       { primary: "#F47920", secondary: "#003DA5", league: "K League 1" },
  "Melbourne Victory":{ primary: "#003DA5", secondary: "#FFFFFF", league: "A-League" },
  "Melbourne City":   { primary: "#009FE3", secondary: "#003087", league: "A-League" },
  "Sydney FC":        { primary: "#009FE3", secondary: "#FFFFFF", league: "A-League" },
  "Western Sydney":   { primary: "#CC0000", secondary: "#000000", league: "A-League" },
  "Western Sydney Wanderers":{ primary: "#CC0000", secondary: "#000000", league: "A-League" },
  "Adelaide United":  { primary: "#CC0000", secondary: "#FFD700", league: "A-League" },
  "Brisbane Roar":    { primary: "#F47920", secondary: "#FFFFFF", league: "A-League" },
  "Perth Glory":      { primary: "#6B2FA0", secondary: "#F47920", league: "A-League" },
  "Central Coast Mariners":{ primary: "#FFD700", secondary: "#003087", league: "A-League" },
  "Wellington Phoenix":{ primary: "#FFD700", secondary: "#000000", league: "A-League" },
  "Macarthur FC":     { primary: "#000000", secondary: "#FFD700", league: "A-League" },
  "Auckland FC":      { primary: "#003DA5", secondary: "#FFFFFF", league: "A-League" },
  "Shanghai Shenhua": { primary: "#003DA5", secondary: "#CC0000", league: "Chinese Super League" },
  "Shanghai Port":    { primary: "#CC0000", secondary: "#FFFFFF", league: "Chinese Super League" },
  "Beijing Guoan":    { primary: "#006B3F", secondary: "#FFD700", league: "Chinese Super League" },
  "Shandong Taishan": { primary: "#F47920", secondary: "#FFFFFF", league: "Chinese Super League" },
  "Guangzhou FC":     { primary: "#CC0000", secondary: "#FFD700", league: "Chinese Super League" },
  "Wuhan Three Towns":{ primary: "#F47920", secondary: "#003DA5", league: "Chinese Super League" },
  "Chengdu Rongcheng":{ primary: "#6B2FA0", secondary: "#FFD700", league: "Chinese Super League" },
  "Tianjin Jinmen Tiger":{ primary: "#003DA5", secondary: "#FFD700", league: "Chinese Super League" },

  // === Liga MX (remaining) ===
  "Monterrey":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "CF Monterrey":     { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "Tigres UANL":      { primary: "#FFD700", secondary: "#003DA5", league: "Liga MX" },
  "Tigres":           { primary: "#FFD700", secondary: "#003DA5", league: "Liga MX" },
  "UNAM Pumas":       { primary: "#003DA5", secondary: "#FFD700", league: "Liga MX" },
  "Pumas":            { primary: "#003DA5", secondary: "#FFD700", league: "Liga MX" },
  "Santos Laguna":    { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga MX" },
  "Toluca":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga MX" },
  "Deportivo Toluca": { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga MX" },
  "León":             { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga MX" },
  "Club León":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Liga MX" },
  "Atlas":            { primary: "#CC0000", secondary: "#000000", league: "Liga MX" },
  "Pachuca":          { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "CF Pachuca":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "Puebla FC":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "Puebla":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "Necaxa":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga MX" },
  "Mazatlán FC":      { primary: "#6B2FA0", secondary: "#FFD700", league: "Liga MX" },
  "Mazatlán":         { primary: "#6B2FA0", secondary: "#FFD700", league: "Liga MX" },
  "Querétaro":        { primary: "#003DA5", secondary: "#FFFFFF", league: "Liga MX" },
  "FC Juárez":        { primary: "#CC0000", secondary: "#000000", league: "Liga MX" },

  // === Brasileirão (remaining) ===
  "Athletico-PR":     { primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "Athletico Paranaense":{ primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "Cuiabá":           { primary: "#006B3F", secondary: "#FFD700", league: "Brasileirão" },
  "Cuiabá EC":        { primary: "#006B3F", secondary: "#FFD700", league: "Brasileirão" },
  "Goiás":            { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "Coritiba":         { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "América-MG":       { primary: "#006B3F", secondary: "#000000", league: "Brasileirão" },
  "América Mineiro":  { primary: "#006B3F", secondary: "#000000", league: "Brasileirão" },
  "Juventude":        { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "EC Juventude":     { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "Red Bull Bragantino":{ primary: "#CC0000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Bragantino":       { primary: "#CC0000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Ceará SC":         { primary: "#000000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Ceará":            { primary: "#000000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Sport Recife":     { primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "Sport":            { primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "Vitória":          { primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "EC Vitória":       { primary: "#CC0000", secondary: "#000000", league: "Brasileirão" },
  "Mirassol":         { primary: "#FFD700", secondary: "#006B3F", league: "Brasileirão" },
  "Mirassol FC":      { primary: "#FFD700", secondary: "#006B3F", league: "Brasileirão" },
  "Chapecoense":      { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "Ponte Preta":      { primary: "#000000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Guarani":          { primary: "#006B3F", secondary: "#FFFFFF", league: "Brasileirão" },
  "Avaí":             { primary: "#003DA5", secondary: "#FFFFFF", league: "Brasileirão" },
  "Náutico":          { primary: "#CC0000", secondary: "#FFFFFF", league: "Brasileirão" },
  "CSA":              { primary: "#003DA5", secondary: "#FFFFFF", league: "Brasileirão" },
  "CRB":              { primary: "#CC0000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Novorizontino":    { primary: "#FFD700", secondary: "#006B3F", league: "Brasileirão" },
  "Vila Nova":        { primary: "#CC0000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Operário-PR":      { primary: "#000000", secondary: "#FFFFFF", league: "Brasileirão" },
  "Santos FC":        { primary: "#000000", secondary: "#FFFFFF", league: "Brasileirão" },

  // === Romanian Liga 1 ===
  "FCSB":             { primary: "#CC0000", secondary: "#003DA5", league: "Liga 1 Romania" },
  "Steaua":           { primary: "#CC0000", secondary: "#003DA5", league: "Liga 1 Romania" },
  "CFR Cluj":         { primary: "#8B0000", secondary: "#FFFFFF", league: "Liga 1 Romania" },
  "Rapid Bucuresti":  { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Liga 1 Romania" },
  "Rapid":            { primary: "#6B2FA0", secondary: "#FFFFFF", league: "Liga 1 Romania" },
  "Universitatea Craiova":{ primary: "#003DA5", secondary: "#FFD700", league: "Liga 1 Romania" },
  "U Craiova":        { primary: "#003DA5", secondary: "#FFD700", league: "Liga 1 Romania" },
  "Dinamo Bucuresti": { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga 1 Romania" },
  "Dinamo":           { primary: "#CC0000", secondary: "#FFFFFF", league: "Liga 1 Romania" },
  "Sepsi OSK":        { primary: "#CC0000", secondary: "#006B3F", league: "Liga 1 Romania" },

  // === League of Ireland ===
  "Shamrock Rovers":  { primary: "#006B3F", secondary: "#FFFFFF", league: "League of Ireland" },
  "Shamrock":         { primary: "#006B3F", secondary: "#FFFFFF", league: "League of Ireland" },
  "Dundalk":          { primary: "#000000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Dundalk FC":       { primary: "#000000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Bohemian FC":      { primary: "#CC0000", secondary: "#000000", league: "League of Ireland" },
  "Bohemians":        { primary: "#CC0000", secondary: "#000000", league: "League of Ireland" },
  "St Patrick's Athletic":{ primary: "#CC0000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Derry City":       { primary: "#CC0000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Sligo Rovers":     { primary: "#CC0000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Shelbourne":       { primary: "#CC0000", secondary: "#FFFFFF", league: "League of Ireland" },
  "Drogheda United":  { primary: "#7C2128", secondary: "#003DA5", league: "League of Ireland" },
  "Waterford FC":     { primary: "#003DA5", secondary: "#FFFFFF", league: "League of Ireland" },
  "Galway United":    { primary: "#7C2128", secondary: "#FFFFFF", league: "League of Ireland" },

  // === Bundesliga (remaining) ===
  "1. FSV Mainz 05":  { primary: "#CC0000", secondary: "#FFFFFF", league: "Bundesliga" },
  "Mainz 05":         { primary: "#CC0000", secondary: "#FFFFFF", league: "Bundesliga" },
  "Mainz":            { primary: "#CC0000", secondary: "#FFFFFF", league: "Bundesliga" },
  "TSG Hoffenheim":   { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga" },
  "Hoffenheim":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga" },
  "FC Heidenheim":    { primary: "#CC0000", secondary: "#003DA5", league: "Bundesliga" },
  "Heidenheim":       { primary: "#CC0000", secondary: "#003DA5", league: "Bundesliga" },
  "VfL Bochum":       { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga" },
  "Bochum":           { primary: "#003DA5", secondary: "#FFFFFF", league: "Bundesliga" },
  "SV Holstein Kiel":  { primary: "#003DA5", secondary: "#CC0000", league: "Bundesliga" },
  "Holstein Kiel":     { primary: "#003DA5", secondary: "#CC0000", league: "Bundesliga" },
  "Kiel":              { primary: "#003DA5", secondary: "#CC0000", league: "Bundesliga" },
};

export const DEFAULT_FALLBACK_COLORS: ClubColors = {
  primary: "#1a1a2e",
  secondary: "#16213e",
};

export function getClubInfo(clubName: string): ClubInfo | null {
  if (!clubName) return null;
  if (CLUB_INFO[clubName]) return CLUB_INFO[clubName];

  const lower = clubName.toLowerCase();
  for (const [key, info] of Object.entries(CLUB_INFO)) {
    if (key.toLowerCase() === lower) return info;
  }
  for (const [key, info] of Object.entries(CLUB_INFO)) {
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) {
      return info;
    }
  }
  return null;
}

export function getClubColors(clubName: string): ClubColors | null {
  const info = getClubInfo(clubName);
  if (!info) return null;
  return { primary: info.primary, secondary: info.secondary };
}

export function getSofifaTeamUrl(sofifaId: string): string {
  return `https://cdn.sofifa.net/teams/${sofifaId}/light_60.png`;
}
