import type { PersonalityStyle } from "@/types/diretoria";

export interface ClubPresidentData {
  name: string;
  personality: PersonalityStyle;
  patience: number;
  description: string;
}

export const CLUB_PRESIDENTS: Record<number, ClubPresidentData> = {
  // ─── LA LIGA ─────────────────────────────────────────────────────────────
  541: { name: "Florentino Pérez", personality: "exigente", patience: 55, description: "Presidente galáctico do Real Madrid, sempre obcecado com títulos e grandes contratações. Exige excelência absoluta e não aceita mediocridade. Reage mal a sequências negativas, mas respeita treinadores que mantêm a identidade vencedora do clube." },
  529: { name: "Joan Laporta", personality: "emocional", patience: 50, description: "Presidente apaixonado do FC Barcelona. Discursa sobre identidade, Cruyffismo e futebol de ataque em todas as ocasiões. Pode ser impulsivo e mudar de posição rapidamente dependendo dos resultados. Valoriza treinadores que entendem o DNA do Barça." },
  530: { name: "Enrique Cerezo", personality: "diplomatico", patience: 65, description: "Presidente experiente do Atlético de Madrid, prefere a estabilidade à espetacularidade. Gere conflitos internos com habilidade e raramente entra em confronto direto com o técnico. Tem paciência razoável e valoriza lealdade acima de tudo." },
  533: { name: "Fernando Roig Negueroles", personality: "conservador", patience: 70, description: "Presidente do Villarreal CF, filho do fundador do projeto. Administra o clube de forma familiar e sustentável. Tem paciência notável com projetos de longo prazo e confia no trabalho do técnico. Prefere desenvolver talentos a fazer gastos astronômicos." },
  532: { name: "Layhoon Chan", personality: "conservador", patience: 65, description: "Presidente do Valencia CF, representante dos interesses do proprietário. Gere com cautela financeira e prefere evitar confrontos públicos. Tem paciência com projetos graduais e busca recuperar a relevância histórica do clube na La Liga." },
  728: { name: "Jokin Aperribay", personality: "analitico", patience: 70, description: "Presidente da Real Sociedad, empresário vasco metódico e criterioso. Construiu um modelo de gestão baseado em formação interna e análise de dados. Tem grande paciência com projetos de longo prazo e valoriza a identidade txuri-urdin." },
  543: { name: "Ángel Haro", personality: "diplomatico", patience: 68, description: "Presidente do Real Betis Balompié, empresário andaluz com gestão equilibrada. Busca manter o clube competitivo sem sacrificar a estabilidade financeira. Valoriza o futebol de qualidade e entende que a torcida verdiblanca exige presença nas competições europeias." },
  536: { name: "José María del Nido Carrasco", personality: "emocional", patience: 50, description: "Presidente do Sevilla FC, apaixonado pelo clube e pela tradição europeia. Envolve-se emocionalmente nos resultados e pode ser impulsivo em momentos de crise. Valoriza a identidade sevilhana e o futebol de alta intensidade." },
  727: { name: "Luis Sabalza", personality: "diplomatico", patience: 65, description: "Presidente do CA Osasuna, dirigente navarro com gestão equilibrada. Administra com prudência financeira e valoriza a estabilidade. Tem paciência com projetos consistentes e cobra que Osasuna mantenha sua posição na La Liga." },
  723: { name: "Jon Uriarte", personality: "diplomatico", patience: 65, description: "Presidente do Athletic Club de Bilbao, guardião da filosofia cantera. Defensor intransigente da política de contratar apenas jogadores bascos ou formados na academia. Tem paciência com o processo de desenvolvimento e exige o futebol agressivo que define o clube." },
  724: { name: "Carlos Mouriño", personality: "emocional", patience: 55, description: "Presidente do Celta de Vigo, empresário apaixonado pelo clube galego. Vive intensamente cada resultado. Valoriza futebol ofensivo e formação de jovens talentos. Tem paciência moderada, mas pode ser impulsivo em momentos de crise." },
  546: { name: "Ángel Torres", personality: "exigente", patience: 50, description: "Presidente do Getafe CF, um dos dirigentes mais intensos da La Liga. Não tem papas na língua e frequentemente entra em conflito com árbitros e outros clubes. Exige que o Getafe seja sempre competitivo e organizado defensivamente." },
  538: { name: "Chen Yansheng", personality: "conservador", patience: 65, description: "Presidente do RCD Espanyol, investidor asiático com visão de longo prazo. Gere com perfil discreto e valoriza estabilidade. Tem paciência com projetos graduais e quer ver o Espanyol consolidado na primeira divisão espanhola." },
  547: { name: "Delfí Geli", personality: "diplomatico", patience: 62, description: "Presidente do Girona FC, dirigente catalão com gestão equilibrada. Administra o projeto surpreendente de ascensão à elite espanhola. Valoriza o futebol de ataque e tem paciência com o processo de adaptação. Cobrar manutenção na La Liga é prioridade." },
  715: { name: "Sergio Fernández Salvadores", personality: "conservador", patience: 68, description: "Presidente do Deportivo Alavés, dirigente basco cauteloso. Administra com foco na sustentabilidade e na permanência na La Liga. Tem paciência com processos de desenvolvimento e valoriza a identidade basca do clube." },
  798: { name: "Miguel Ángel Ramírez", personality: "emocional", patience: 55, description: "Presidente da UD Las Palmas, apaixonado pelo futebol canário. Cobra que o clube represente com orgulho as Ilhas Canárias na La Liga. Tem paciência moderada e vive intensamente os resultados da equipe." },

  // ─── PREMIER LEAGUE ──────────────────────────────────────────────────────
  40: { name: "Tom Werner", personality: "conservador", patience: 60, description: "Chairman do Liverpool FC. Toma decisões com base em análise de dados e sustentabilidade financeira. Não costuma fazer movimentos impulsivos no mercado, preferindo o desenvolvimento de talentos. Dá suporte ao projeto técnico no longo prazo." },
  50: { name: "Khaldoon Al Mubarak", personality: "exigente", patience: 45, description: "Presidente do Manchester City, representante dos investidores de Abu Dhabi. Articulado e ambicioso, exige que o clube mantenha os mais altos padrões mundiais. Tem foco absoluto em títulos e não aceita regressão." },
  33: { name: "Jim Ratcliffe", personality: "exigente", patience: 45, description: "Co-proprietário do Manchester United com mandato para recuperar o clube de uma crise longa. Perfil de empresário de alta performance, acostumado com eficiência e resultados. Exige que o clube volte a ser referência mundial no menor tempo possível." },
  42: { name: "Stan Kroenke", personality: "analitico", patience: 75, description: "Proprietário e presidente do Arsenal, empresário americano do ramo esportivo. Mantém distância da gestão diária e delega decisões esportivas à diretoria especializada. Tem paciência considerável para projetos de longo prazo e valoriza estabilidade financeira." },
  49: { name: "Todd Boehly", personality: "agressivo", patience: 40, description: "Co-proprietário e co-presidente executivo do Chelsea. Empresário americano que chegou com investimentos massivos e ambições imediatas. Envolveu-se diretamente em contratações e pode ser impulsivo nas decisões. Espera resultados rápidos." },
  47: { name: "Daniel Levy", personality: "analitico", patience: 55, description: "Chairman do Tottenham Hotspur, negociador habilidoso e profundamente detalhista. Controla finanças com rigor e raramente aceita pagar além do considerado justo. Tem expectativas altas, mas tende a apoiar o técnico por um período razoável." },
  48: { name: "Daniel Kretinsky", personality: "conservador", patience: 65, description: "Co-proprietário do West Ham United, empresário tcheco do setor de energia. Tem visão de longo prazo e valoriza a estabilidade. Não costuma fazer intervenções públicas e deixa a gestão esportiva para os profissionais." },
  51: { name: "Tony Bloom", personality: "analitico", patience: 72, description: "Dono e presidente do Brighton & Hove Albion, referência global em análise de dados no futebol. Construiu um modelo de gestão baseado em data analytics que se tornou referência na Premier League. Tem grande paciência com projetos alinhados à filosofia do clube." },
  45: { name: "Bill Kenwright", personality: "emocional", patience: 58, description: "Presidente do Everton FC, toffee de coração e dirigente histórico do clube. Apaixonado pelo clube e pela torcida de Goodison Park. Sente profundamente cada resultado e cobra comprometimento com a camisa azul." },
  66: { name: "Nassef Sawiris", personality: "diplomatico", patience: 68, description: "Co-proprietário do Aston Villa, bilionário egípcio-britânico com ambições europeias. Investiu fortemente no clube e quer consolidar o Villa entre os grandes da Premier League. Entende que levar o Villa de volta à Europa foi um passo histórico e quer ir além." },
  55: { name: "Matthew Benham", personality: "analitico", patience: 70, description: "Dono do Brentford FC, especialista em modelagem matemática e apostas esportivas. Construiu um dos modelos de gestão mais inovadores do futebol inglês. Tem paciência com processos bem fundamentados. Valoriza eficiência e coerência do modelo de gestão." },
  65: { name: "Evangelos Marinakis", personality: "exigente", patience: 48, description: "Proprietário do Nottingham Forest, armador grego com grandes ambições. Investe pesado e espera resultados rápidos em troca. Não é conhecido pela paciência. Quer ver o Forest de volta às glórias europeias e não aceita luta contra o rebaixamento." },
  34: { name: "Yasir Al-Rumayyan", personality: "diplomatico", patience: 70, description: "Presidente do Newcastle United, representante do PIF saudita. Toma decisões estratégicas de forma deliberada. Entende que o projeto de reconstrução do clube é de longo prazo e dá suporte ao corpo técnico enquanto vê progresso." },
  46: { name: "Aiyawatt Srivaddhanaprabha", personality: "diplomatico", patience: 65, description: "Presidente do Leicester City, filho do falecido fundador do projeto vencedor. Mantém a visão do pai de construir um clube sólido e competitivo. Tem paciência com projetos de longo prazo e valoriza a família Leicester." },
  52: { name: "Steve Parish", personality: "diplomatico", patience: 63, description: "Co-proprietário e presidente do Crystal Palace FC. Torcedor histórico que se tornou dirigente. Tem equilíbrio entre paixão pelo clube e visão empresarial. Valoriza a identidade de Selhurst Park e quer ver o Palace competitivo na Premier League." },
  44: { name: "Jeff Shi", personality: "diplomatico", patience: 68, description: "Presidente do Wolverhampton Wanderers, representante da Fosun International. Administra o clube com perfil discreto e visão de longo prazo. Quer consolidar os Wolves como clube relevante da Premier League com identidade clara." },
  35: { name: "Bill Foley", personality: "analitico", patience: 63, description: "Proprietário do AFC Bournemouth, investidor americano com portfólio esportivo diversificado. Tem abordagem analítica e valoriza eficiência. Espera que o Bournemouth consolide sua presença na elite inglesa com futebol organizado." },
  36: { name: "Shahid Khan", personality: "conservador", patience: 70, description: "Proprietário do Fulham FC, empresário paquistanês-americano do setor automotivo. Tem visão de longo prazo e investe de forma progressiva. Valoriza a permanência do Fulham na Premier League como base para um projeto ambicioso." },
  67: { name: "Mark Detmer", personality: "conservador", patience: 68, description: "Co-proprietário do Ipswich Town, americano do projeto Gamechanger 20. Geriu o projeto que levou o Ipswich do terceiro nível ao topo do futebol inglês. Tem paciência com o projeto de desenvolvimento e entende que a adaptação à Premier League é um processo." },
  41: { name: "Dragan Solak", personality: "agressivo", patience: 50, description: "Proprietário do Southampton FC, empresário sérvio que investiu no clube. Tem expectativas altas após os investimentos realizados no elenco e na infraestrutura. Pode ser impulsivo em momentos de crise e cobra alta performance do corpo técnico." },

  // ─── BUNDESLIGA ──────────────────────────────────────────────────────────
  157: { name: "Herbert Hainer", personality: "diplomatico", patience: 65, description: "Presidente do Bayern de Munique, ex-CEO da Adidas com perfil corporativo e polido. Mantém a estrutura vencedora do clube funcionando com profissionalismo. Tem expectativas altíssimas dada a história do clube, mas dá suporte ao projeto técnico enquanto os resultados se mantêm competitivos." },
  165: { name: "Hans-Joachim Watzke", personality: "emocional", patience: 55, description: "CEO do Borussia Dortmund, voz da identidade amarelo-preta. Apaixonado pelo clube e pela conexão com a torcida do Muro Amarelo. Envolve-se emocionalmente nos resultados e cobra o mesmo nível de comprometimento do corpo técnico." },
  168: { name: "Fernando Carro", personality: "exigente", patience: 50, description: "CEO do Bayer Leverkusen numa era de ambições renovadas. Meticuloso e altamente exigente com a performance coletiva. Após o título histórico da Bundesliga, as expectativas no clube subiram muito. Não aceita regressão." },
  173: { name: "Oliver Mintzlaff", personality: "agressivo", patience: 48, description: "CEO do RB Leipzig, executivo com DNA Red Bull de alta performance. Orientado para resultados e data analytics, não tolera mediocridade. Tem pouca paciência para sequências ruins e pode tomar decisões rápidas." },
  169: { name: "Peter Fischer", personality: "emocional", patience: 55, description: "Presidente do Eintracht Frankfurt, um dos dirigentes mais apaixonados do futebol alemão. Não tem medo de se posicionar politicamente e defende os valores do clube com intensidade. Vive os resultados intensamente e quer que o Eintracht seja sempre competitivo." },
  161: { name: "Claus Vogt", personality: "diplomatico", patience: 65, description: "Presidente do VfB Stuttgart, eleito pelos sócios do clube. Gere com transparência e busca manter o Stuttgart como clube do povo. Tem paciência moderada e valoriza o futebol jovem e progressivo." },
  176: { name: "Marcel Schäfer", personality: "analitico", patience: 62, description: "Diretor esportivo do VfL Wolfsburg, ex-jogador com perfil analítico. Administra o clube com apoio do grupo Volkswagen. Valoriza organização, dados e planejamento de longo prazo. Tem paciência razoável, mas espera que o técnico mantenha a equipe competitiva." },
  163: { name: "Roland Virkus", personality: "conservador", patience: 68, description: "Diretor geral do Borussia Mönchengladbach, gestor experiente com foco em sustentabilidade. Administra o clube priorizando equilíbrio financeiro e desenvolvimento de jovens. Tem paciência com processos de reconstrução." },
  172: { name: "Dirk Zingler", personality: "emocional", patience: 55, description: "Presidente do Union Berlin, clube com identidade única e torcida apaixonadíssima. Construiu um projeto surpreendente que levou o Union ao futebol europeu. Vive intensamente cada jogo e é muito próximo da torcida." },
  162: { name: "Hubertus Hess-Grunewald", personality: "analitico", patience: 65, description: "Presidente do Werder Bremen, clube com história rica na Bundesliga. Administra com critério e preza pela formação de jovens talentos. Tem paciência moderada e valoriza o futebol ofensivo que sempre caracterizou o Werder." },
  167: { name: "Oke Göttlich", personality: "diplomatico", patience: 60, description: "Presidente do FC St. Pauli em Hamburgo — clube com forte identidade política e social. Defende os valores progressistas do clube com convicção. Tem paciência com projetos que respeitem a identidade do clube, mas cobra competitividade na Bundesliga." },
  170: { name: "Stefan Hofmann", personality: "conservador", patience: 65, description: "Presidente do FSV Mainz 05, dirigente com gestão séria e responsável. Administra o clube com equilíbrio financeiro e foco na permanência na Bundesliga. Tem paciência com processos de desenvolvimento e valoriza a identidade do clube renano." },
  171: { name: "Klaus Hofmann", personality: "diplomatico", patience: 68, description: "Presidente do FC Augsburg, dirigente bávaro com gestão equilibrada. Administra o clube de forma sustentável e valoriza a permanência na Bundesliga. Tem paciência com projetos de desenvolvimento e cobra comprometimento dos jogadores." },
  159: { name: "Kay Bernstein", personality: "emocional", patience: 52, description: "Presidente do Hertha BSC de Berlim, torcedor fanático que se tornou dirigente. Apaixonado pelo clube e comprometido com sua recuperação. Pode ser impulsivo em momentos de crise e não esconde seus sentimentos. Valoriza jogadores que entendam a grandeza histórica do clube." },
  174: { name: "Oke Göttlich", personality: "diplomatico", patience: 64, description: "Dirigente do SC Freiburg, clube que cresceu de forma sustentável na Bundesliga. Administra com equilíbrio e valoriza o futebol organizado. Tem paciência com projetos de longo prazo e cobra comprometimento com a identidade do clube." },
  160: { name: "Marcell Jansen", personality: "analitico", patience: 60, description: "Presidente do Hamburger SV, ex-jogador com perfil analítico. Administra o clube histórico que busca retornar à Bundesliga. Tem paciência com processos estruturados e valoriza a formação de jovens. Cobra competitividade e determinação para o retorno à elite." },
  164: { name: "Werner Wolf", personality: "emocional", patience: 52, description: "Presidente do 1. FC Köln, dirigente apaixonado pelo clube renano. Vive intensamente os resultados e não esconde sua paixão pelo Effzeh. Tem paciência moderada, mas sente a pressão constante da torcida para que o Köln seja competitivo." },
  175: { name: "Holger Sanwald", personality: "analitico", patience: 65, description: "Presidente do FC Heidenheim, dirigente que conduziu o clube à história. Administra com dados e visão estratégica. Tem paciência com o processo de adaptação à Bundesliga e valoriza o trabalho consistente que trouxe o pequeno clube à elite do futebol alemão." },

  // ─── SERIE A ─────────────────────────────────────────────────────────────
  489: { name: "Paolo Scaroni", personality: "analitico", patience: 60, description: "Presidente do AC Milan com perfil empresarial e racional. Toma decisões baseadas em dados financeiros e de desempenho. Reage com frieza a resultados ruins, mas exige explicações claras do corpo técnico. Valoriza a recuperação histórica do clube." },
  505: { name: "Giuseppe Marotta", personality: "analitico", patience: 70, description: "CEO e presidente-executivo da Inter de Milão, referência em gestão esportiva italiana. Metódico, criterioso e sempre bem-informado sobre mercado de transferências. Dá suporte ao técnico desde que os números justifiquem as escolhas. Tem visão estratégica de longo prazo." },
  492: { name: "Aurelio De Laurentiis", personality: "emocional", patience: 40, description: "Presidente temperamental do SSC Napoli, produtor cinematográfico de coração apaixonado. Envolve-se diretamente em decisões técnicas e não hesita em expressar insatisfação publicamente. Pode agir de forma impulsiva, mas é extremamente generoso quando as coisas vão bem." },
  496: { name: "Gianluca Ferrero", personality: "conservador", patience: 65, description: "Presidente da Juventus num momento de reconstrução do clube. Adota postura cautelosa e prioriza a sustentabilidade financeira após anos de instabilidade. Apoia o projeto técnico enquanto vê evolução, mas é sensível à pressão da torcida bianconera." },
  487: { name: "Dan Friedkin", personality: "conservador", patience: 70, description: "Presidente da AS Roma, investidor americano que assumiu o clube com ambições europeias. Gere o clube de forma discreta. Tem paciência com projetos de longo prazo, mas espera profissionalismo e dedicação. Entende a importância cultural do futebol romano." },
  488: { name: "Claudio Lotito", personality: "exigente", patience: 45, description: "Presidente da SS Lazio, político e empresário com estilo de liderança autoritário. Controla o clube com mão-de-ferro e não hesita em confrontar técnicos ou jogadores quando os resultados desagradam. Extremamente exigente, mas leal aos que entregam resultados." },
  500: { name: "Antonio Percassi", personality: "diplomatico", patience: 72, description: "Presidente da Atalanta, empresário bergamasco que transformou o clube numa potência europeia. Tem visão de longo prazo e paciência para projetos consistentes. Apoia o técnico desde que o estilo de jogo continue a encantar e produzir resultados." },
  502: { name: "Rocco Commisso", personality: "emocional", patience: 52, description: "Presidente da Fiorentina, empresário ítalo-americano apaixonado pelo clube viola. Investe de forma ambiciosa e tem grande expectativa de retorno. Pode ser emocional e vocal perante a mídia quando as coisas não correm bem." },
  497: { name: "Urbano Cairo", personality: "analitico", patience: 60, description: "Presidente do Torino FC, editor de mídia com perfil analítico e cauteloso. Administra o clube com foco na sustentabilidade financeira e não costuma fazer grandes gastos. Tem paciência moderada e valoriza treinadores que desenvolvem jovens e organizam bem a equipe." },
  504: { name: "Joey Saputo", personality: "conservador", patience: 68, description: "Presidente do Bologna FC, empresário canadense que transformou o clube. Gere de forma profissional com foco no desenvolvimento sustentável. Tem paciência com projetos de longo prazo e valoriza o crescimento gradual do clube." },
  494: { name: "Giampaolo Pozzo", personality: "analitico", patience: 70, description: "Presidente do Udinese Calcio, empresário que controla o clube há décadas. Especialista em descobrir talentos e vendê-los para grandes clubes europeus. Tem visão clara do modelo de negócio do Udinese e paciência para projetos sustentáveis." },
  495: { name: "Tommaso Giulini", personality: "diplomatico", patience: 63, description: "Presidente do Cagliari Calcio, empresário sardo com amor pelo clube da ilha. Tem gestão equilibrada e paciência com processos de desenvolvimento. Cobra que o Cagliari mantenha sua presença na Serie A e represente bem a Sardegna." },
  503: { name: "Fabrizio Corsi", personality: "conservador", patience: 68, description: "Presidente do Empoli FC, dirigente toscano com gestão familiar e sustentável. Transformou o Empoli num clube que constantemente desafia os grandes da Serie A. Tem paciência com projetos de formação de jovens e valoriza o futebol organizado." },
  498: { name: "Giovanni Carnevali", personality: "analitico", patience: 65, description: "Presidente do Sassuolo, dirigente que trouxe o clube à Serie A. Especialista em revelação de talentos e gestão eficiente. Tem visão de longo prazo e paciência com projetos estruturados. Valoriza o desenvolvimento de jovens jogadores." },
  493: { name: "Marco Lanna", personality: "emocional", patience: 55, description: "Presidente da Sampdoria, ex-jogador do clube apaixonado pelo Doria. Vive intensamente os resultados e cobra comprometimento com a camisa blucerchiata. Tem paciência moderada e valoriza a tradição do clube genovês." },
  507: { name: "Maurizio Setti", personality: "exigente", patience: 50, description: "Presidente do Hellas Verona, empresário com gestão exigente. Tem expectativas claras e cobra comprometimento do corpo técnico. Pode ser impulsivo quando os resultados não satisfazem. Valoriza o Verona competitivo na Serie A." },
  499: { name: "Adriano Galliani", personality: "diplomatico", patience: 65, description: "CEO do AC Monza e lenda do futebol italiano. Experiente negociador e gestor com décadas de história no futebol. Tem paciência com projetos coerentes e valoriza o trabalho bem feito. O Monza é um projeto especial que Galliani quer consolidar na Serie A." },
  508: { name: "Saverio Sticchi Damiani", personality: "diplomatico", patience: 65, description: "Presidente do US Lecce, dirigente pugliese com gestão equilibrada. Administra o clube com foco na permanência na Serie A. Tem paciência com processos de desenvolvimento e cobra comprometimento dos jogadores com a camisa giallorossa." },

  // ─── LIGUE 1 ─────────────────────────────────────────────────────────────
  85: { name: "Nasser Al-Khelaïfi", personality: "agressivo", patience: 35, description: "Presidente do Paris Saint-Germain e figura do Qatar Sports Investments. Movimenta o futebol mundial com seu poder financeiro e ambição desmedida. Não aceita nada menos que a Liga dos Campeões. Pode ser impulsivo e mudar a diretriz do clube abruptamente." },
  80: { name: "John Textor", personality: "agressivo", patience: 45, description: "Proprietário do Olympique Lyonnais e do Eagle Football Group. Empresário americano com ambições globais no futebol. Não hesita em confrontar publicamente adversários e reguladores. Espera resultados expressivos do investimento realizado no Lyon." },
  81: { name: "Pablo Longoria", personality: "analitico", patience: 60, description: "Presidente do Olympique de Marseille, jovem dirigente espanhol com formação em análise de dados. Construiu uma reputação como descobridor de talentos e gestor inovador. Tem visão estratégica clara e paciência para projetos coerentes." },
  91: { name: "Dmitry Rybolovlev", personality: "exigente", patience: 50, description: "Presidente do AS Monaco, bilionário russo que investiu fortemente no clube do principado. Tem grandes expectativas e não aceita o Monaco fora das primeiras posições da Ligue 1. Costuma intervir diretamente nas decisões quando os resultados não satisfazem." },
  93: { name: "Jean-Pierre Rivère", personality: "diplomatico", patience: 65, description: "Presidente do OGC Nice, dirigente experiente que trouxe estabilidade ao clube da Côte d'Azur. Gere com equilíbrio entre ambições esportivas e realidade financeira. O investimento dos donos ingleses elevou as expectativas de um clube que quer ser regular na Europa." },
  95: { name: "Nicolas Holveck", personality: "analitico", patience: 65, description: "Presidente do Stade Rennais, dirigente breton com gestão profissional. Administra o clube com visão de longo prazo e foco no desenvolvimento de jovens. Tem paciência com projetos coerentes e valoriza o futebol organizado que posiciona Rennes na elite francesa." },
  96: { name: "Joseph Oughourlian", personality: "analitico", patience: 68, description: "Presidente do RC Lens, investidor com visão de longo prazo para o clube mineiro. Transformou o Lens numa força surpreendente da Ligue 1. Valoriza coesão de grupo e consistência. Tem paciência com o projeto, mas espera que o clube se mantenha competitivo." },
  111: { name: "Laurent Nicollin", personality: "emocional", patience: 52, description: "Presidente do Montpellier Hérault SC, filho do fundador e apaixonado pelo clube. Vive intensamente os resultados e cobra comprometimento com a camisa azul e laranja. Tem paciência moderada e valoriza o futebol que trouxe o Montpellier ao título da Ligue 1." },
  98: { name: "Olivier Létang", personality: "exigente", patience: 52, description: "Presidente do LOSC Lille, dirigente ambicioso que quer devolver o clube ao topo do futebol francês. Não esconde suas expectativas de formar equipes capazes de competir na Champions League. Valoriza o modelo de revelação de talentos pelo qual o Lille é reconhecido mundialmente." },
  106: { name: "Nicolas Hernandez", personality: "diplomatico", patience: 62, description: "Presidente do FC Nantes, dirigente que navega entre tradição e modernidade. Administra o clube histórico com equilíbrio e busca manter o Nantes na Ligue 1. Tem paciência com processos de desenvolvimento e valoriza a identidade do futebol da cidade do Loire." },
  84: { name: "Damien Comolli", personality: "analitico", patience: 65, description: "Presidente do Toulouse FC, dirigente com visão analítica e data-driven. Administra o clube com foco em eficiência e desenvolvimento de jovens. Tem paciência com projetos estruturados e valoriza o futebol ofensivo que volta a animar a cidade violeta." },
  109: { name: "Marc Keller", personality: "diplomatico", patience: 63, description: "Presidente do RC Strasbourg, ex-jogador com gestão equilibrada. Administra o clube alsaciano com foco na identidade local e na permanência na Ligue 1. Tem paciência com projetos de desenvolvimento e valoriza o futebol organizado." },
  103: { name: "Jean-Pierre Caillot", personality: "conservador", patience: 67, description: "Presidente do Stade de Reims, dirigente com gestão séria e responsável. Transformou o Reims num clube respeitado na Ligue 1. Tem paciência com processos de desenvolvimento e valoriza a formação de jovens. Cobra comprometimento e organização." },
  83: { name: "Jean-Michel Roussier", personality: "conservador", patience: 65, description: "Presidente do Havre AC, dirigente que conduziu o histórico clube de volta à Ligue 1. Administra com equilíbrio financeiro e foco na sustentabilidade. Tem paciência com o processo de adaptação à elite e valoriza o futebol organizado." },

  // ─── LIGA PORTUGAL ───────────────────────────────────────────────────────
  212: { name: "André Villas-Boas", personality: "analitico", patience: 62, description: "Presidente do FC Porto, ex-treinador e técnico que conhece o futebol profundamente. Tem visão analítica das contratações e do jogo. Cobra que o Porto mantenha a hegemonia no futebol português e seja competitivo na Champions League." },
  211: { name: "Rui Costa", personality: "exigente", patience: 52, description: "Presidente do Sport Lisboa e Benfica, lenda do clube que assumiu a direção. Tem expectativas altíssimas e não aceita que o Benfica perca a liderança do futebol português. Exige títulos nacionais e participação ativa na Champions League." },
  228: { name: "Frederico Varandas", personality: "diplomatico", patience: 65, description: "Presidente do Sporting CP, médico que assumiu o clube num momento difícil. Trouxe equilíbrio financeiro e construiu um projeto vencedor. Tem paciência com processos bem estruturados e cobra competitividade nacional e internacional." },
  226: { name: "António Salvador", personality: "conservador", patience: 68, description: "Presidente do Sporting Clube de Braga, empresário com visão de longo prazo. Transformou o Braga numa força regular do futebol europeu. Tem paciência com projetos sustentáveis e cobra que o Braga mantenha sua posição no top 3 português." },
  217: { name: "António Miguel Cardoso", personality: "emocional", patience: 58, description: "Presidente da Vitória SC de Guimarães, dirigente minhoto apaixonado pelo clube. Vive intensamente os resultados e cobra comprometimento com a camisa vitoriosa. Tem paciência moderada e valoriza o futebol competitivo que é tradição do clube." },

  // ─── EREDIVISIE ──────────────────────────────────────────────────────────
  194: { name: "Jan van Halst", personality: "diplomatico", patience: 62, description: "Presidente do AFC Ajax, clube com tradição de revelação de talentos mundialmente reconhecida. Gere num momento de reconstrução após anos difíceis. Tem paciência com o processo e valoriza a identidade de jogo ofensivo que fez o Ajax famoso." },
  197: { name: "Toon Gerbrands", personality: "analitico", patience: 65, description: "CEO do PSV Eindhoven, gestão profissional com foco em data analytics. O PSV vive um dos melhores momentos recentes e as expectativas são altas. Tem paciência com projetos coerentes e valoriza a formação de jovens." },
  193: { name: "Dennis te Kloese", personality: "conservador", patience: 68, description: "CEO do Feyenoord Rotterdam, clube renascido com nova geração de talentos. Administra de forma profissional e valoriza o desenvolvimento sustentável. Tem paciência moderada e quer consolidar o Feyenoord entre os melhores clubes holandeses." },
  198: { name: "Wouter Gudde", personality: "analitico", patience: 65, description: "Diretor executivo do AZ Alkmaar, dirigente holandês com gestão profissional. Administra o clube com foco em revelação de talentos e futebol competitivo. Tem paciência com projetos de desenvolvimento e valoriza a identidade do futebol do Norte da Holanda." },
  201: { name: "Jan Willem van Dop", personality: "diplomatico", patience: 63, description: "Presidente do FC Utrecht, dirigente holandês com gestão equilibrada. Administra o clube com foco em sustentabilidade e competitividade na Eredivisie. Tem paciência com processos de desenvolvimento e valoriza o futebol organizado." },
  195: { name: "Paul van der Kraan", personality: "conservador", patience: 65, description: "Presidente do FC Twente, dirigente enschedeano com gestão responsável. Administra o clube com foco na permanência entre os melhores da Eredivisie. Tem paciência com processos de desenvolvimento e valoriza a identidade regional do clube." },

  // ─── SCOTTISH PREMIERSHIP ────────────────────────────────────────────────
  246: { name: "Peter Lawwell", personality: "analitico", patience: 68, description: "CEO do Celtic FC, clube histórico de Glasgow com identidade única. Administra com foco no equilíbrio financeiro e na competitividade nacional. Tem paciência com projetos coerentes que mantenham o Celtic dominante na Scottish Premiership e classificado para a Champions League." },
  247: { name: "John Bennett", personality: "diplomatico", patience: 63, description: "Presidente do Rangers FC, clube histórico de Glasgow. Gere num momento de reconstrução e disputa intensa com o Celtic. Tem paciência com processos bem estruturados e valoriza o comprometimento com as cores azuis. Cobra que o Rangers vença o Old Firm." },

  // ─── SÜPER LIG ───────────────────────────────────────────────────────────
  645: { name: "Dursun Özbek", personality: "emocional", patience: 48, description: "Presidente do Galatasaray SK, um dos clubes mais apaixonantes da Turquia. Vive intensamente a rivalidade com Fenerbahçe e Beşiktaş. Não esconde suas emoções e pode ser impulsivo em momentos de derrota. Exige dominância na Süper Lig e presença europeia." },
  641: { name: "Ali Koç", personality: "agressivo", patience: 45, description: "Presidente do Fenerbahçe SK, empresário com grandes ambições para o clube amarelo-azul. Cobra forte da equipe e não aceita que o Fenerbahçe fique atrás do Galatasaray. Pode ser impulsivo e entra frequentemente em polêmicas com árbitros e rivais." },
  642: { name: "Hasan Arat", personality: "exigente", patience: 50, description: "Presidente do Beşiktaş JK, clube histórico de Istambul. Exige comprometimento com a camisa preta e branca e cobra que o time seja competitivo. Tem paciência limitada com sequências ruins e pode tomar decisões rápidas quando os resultados frustram." },
  643: { name: "İbrahim Hacıosmanoğlu", personality: "emocional", patience: 52, description: "Presidente do Trabzonspor, clube símbolo do Mar Negro turco. Apaixonado pelo clube e pela torcida bordo-mavi. Pode ser extremamente emocional e provocativo nas declarações públicas. Exige que o Trabzonspor seja competitivo nas competições europeias." },

  // ─── RUSSIAN PREMIER LEAGUE ──────────────────────────────────────────────
  370: { name: "Leonid Fedun", personality: "exigente", patience: 48, description: "Presidente do Spartak Moscou, bilionário russo com grandes ambições. Investe fortemente no clube vermelho-branco e exige títulos. Pode ser impulsivo em momentos de crise e não hesita em fazer mudanças drásticas. A história do Spartak exige sempre comprometimento máximo." },
  371: { name: "Yevgeny Giner", personality: "analitico", patience: 62, description: "Presidente do CSKA Moscou, dirigente com gestão profissional e analítica. Administra o clube com critério e valoriza a consistência. Tem paciência moderada com projetos coerentes e cobra que o CSKA mantenha sua competitividade no futebol russo." },
  373: { name: "Alexander Medvedev", personality: "diplomatico", patience: 65, description: "Presidente do Zenit São Petersburgo, dirigente experiente com gestão equilibrada. O clube recebe forte apoio do Gazprom e tem ambições europeias. Tem paciência com projetos de longo prazo e cobra que o Zenit seja sempre dominante na Rússia." },
  374: { name: "Ilya Gerkus", personality: "conservador", patience: 65, description: "Presidente do Lokomotiv Moscou, dirigente ferroviário com gestão cautelosa. Administra o clube com foco na estabilidade e na competitividade na Premier Liga russa. Tem paciência com processos de desenvolvimento e valoriza futebol organizado." },

  // ─── BRASILEIRÃO ─────────────────────────────────────────────────────────
  568: { name: "Rodrigo Dunshee", personality: "exigente", patience: 50, description: "Presidente do Clube de Regatas do Flamengo, advogado e dirigente de longa data. Representa as ambições nacionais e internacionais do maior clube do Brasil. Exige títulos e não aceita mediocridade, dada a dimensão histórica e financeira do Flamengo." },
  119: { name: "Leila Pereira", personality: "agressivo", patience: 40, description: "Presidente da SE Palmeiras, empresária dona da Crefisa. Investiu massivamente no clube e cobra resultados proporcionais. É direta, impulsiva e não hesita em manifestar insatisfação publicamente. Tem expectativas altíssimas e pode ser implacável com técnicos que não entregam títulos." },
  118: { name: "Julio Casares", personality: "conservador", patience: 65, description: "Presidente do São Paulo Futebol Clube, médico e dirigente respeitado. Administra o clube com foco na recuperação financeira e esportiva. Dá suporte ao projeto técnico enquanto vê evolução, mas cobra competitividade. Valoriza a história tricolor e busca devolver o São Paulo ao topo." },
  121: { name: "Marcelo Teixeira", personality: "emocional", patience: 55, description: "Presidente do Santos FC, personagem histórico do clube praiano. Apaixonado pelo futebol de ataque e pela tradição santista. Cobra que o Santos jogue bonito e seja competitivo. Reage mal a derrotas dentro da Vila Belmiro e pode ser vocal na sua insatisfação." },
  116: { name: "Augusto Melo", personality: "diplomatico", patience: 60, description: "Presidente do Sport Club Corinthians Paulista, político experiente no ambiente clube. Navega entre diferentes grupos de torcidas e interesses. Tenta equilibrar as demandas esportivas com as limitações financeiras do clube. Valoriza a lealdade dos jogadores com a camisa alvinegra." },
  130: { name: "Alberto Guerra", personality: "analitico", patience: 60, description: "Presidente do Grêmio Foot-Ball Porto Alegrense, dirigente focado na reestruturação do clube. Analisa o desempenho com dados e tem postura racional. Cobra competitividade na Série A e valoriza as categorias de base e a identidade defensiva do clube." },
  115: { name: "Alessandro Barcellos", personality: "diplomatico", patience: 65, description: "Presidente do Sport Club Internacional, ex-goleiro e dirigente carismático. Transita bem entre torcida, jogadores e imprensa. Tem paciência com projetos de desenvolvimento e cobra comprometimento com a camisa vermelha." },
  124: { name: "Mário Celso Petraglia", personality: "exigente", patience: 50, description: "Presidente do Athletico Paranaense, um dos dirigentes mais influentes do futebol brasileiro. Não se contenta com resultados mediocres e exige que o Furacão seja protagonista. Tem paciência limitada com sequências negativas. Foi arquiteto do sucesso recente do clube na Copa Sul-Americana." },
  126: { name: "Pedro Lourenço", personality: "agressivo", patience: 45, description: "Presidente do Cruzeiro Esporte Clube, empresário que assumiu o clube na SAF e investiu pesado. Tem perfil empreendedor e não hesita em tomar decisões rápidas. Espera retorno imediato do investimento em forma de títulos e projeção nacional." },
  127: { name: "Sérgio Coelho", personality: "exigente", patience: 50, description: "Presidente do Clube Atlético Mineiro, dirigente ambicioso que conduziu o clube à Copa Libertadores. Não se contenta com resultados mediocres e exige que o Galo seja protagonista em todas as competições. Tem paciência limitada com sequências negativas." },
  120: { name: "Mário Bittencourt", personality: "diplomatico", patience: 60, description: "Presidente do Fluminense Football Club, advogado e dirigente articulado. Administra bem as relações políticas no futebol brasileiro. Tem paciência com projetos de longo prazo e valoriza a identidade do Fluminense. Cobra competitividade mas entende os ciclos do futebol." },
  7323: { name: "John Textor", personality: "agressivo", patience: 45, description: "Presidente do Botafogo de Futebol e Regatas, empresário americano dono do Eagle Football Group. Movimenta o clube com recursos internacionais e ambições de escala global. Não hesita em confrontar a mídia e dirigentes rivais. Espera resultados expressivos dos investimentos realizados." },
  128: { name: "Pedrinho", personality: "emocional", patience: 52, description: "Presidente do Club de Regatas Vasco da Gama, ex-jogador e dirigente apaixonado. Vive intensamente os resultados do clube cruzmaltino. Valoriza a grandeza histórica do Vasco e cobra que o clube ocupe posição de destaque no futebol brasileiro." },
  139: { name: "Alex Santiago", personality: "conservador", patience: 65, description: "Presidente do Fortaleza Esporte Clube, dirigente que conduziu o clube a uma ascensão histórica. Administra com equilíbrio financeiro e investe de forma criteriosa. Tem paciência com projetos consistentes e valoriza o futebol organizado e competitivo." },
  131: { name: "Guilherme Bellintani", personality: "diplomatico", patience: 62, description: "Presidente do Esporte Clube Bahia, advogado e dirigente moderno. Administra bem as relações políticas e institucionais do clube. Tem paciência moderada e cobra que o Bahia seja competitivo e represente o Nordeste com qualidade." },
  140: { name: "Yuri Romão", personality: "emocional", patience: 55, description: "Presidente do Sport Club do Recife, dirigente pernambucano apaixonado pelo clube vermelho-preto. Vive intensamente cada resultado e cobra comprometimento com a camisa leão. Tem paciência moderada e valoriza a identidade nordestina do clube." },
  144: { name: "João Paulo Silva", personality: "diplomatico", patience: 60, description: "Presidente do Ceará Sporting Club, dirigente cearense com gestão equilibrada. Administra o clube com foco na sustentabilidade e na competitividade na Série A. Tem paciência com processos de desenvolvimento e valoriza o futebol organizado." },
  147: { name: "Delfim Peixoto", personality: "conservador", patience: 65, description: "Presidente do América Mineiro, dirigente com gestão cautelosa e focada na sustentabilidade. Administra o clube dentro de suas possibilidades e valoriza a permanência na Série A como conquista importante. Tem paciência com processos de desenvolvimento." },
  145: { name: "Paulo Rogério", personality: "emocional", patience: 55, description: "Presidente do Goiás Esporte Clube, dirigente goiano apaixonado pelo clube esmeraldino. Vive intensamente os resultados e cobra comprometimento com a camisa verde. Tem paciência moderada e valoriza o futebol competitivo que posiciona Goiás no cenário nacional." },
  150: { name: "Gustavo Fruet", personality: "diplomatico", patience: 63, description: "Presidente do Coritiba Foot Ball Club, dirigente paranaense com gestão equilibrada. Administra o clube com foco na sustentabilidade e na competitividade. Tem paciência com projetos de desenvolvimento e valoriza a identidade branca e verde do clube histórico." },
  146: { name: "José Graeff", personality: "conservador", patience: 65, description: "Presidente do Cuiabá Esporte Clube, dirigente do centro-oeste com gestão responsável. Administra o clube que cresceu rapidamente ao futebol profissional de alto nível. Tem paciência com processos de desenvolvimento e cobra comprometimento na Série A." },
  158: { name: "Thiago Scuro", personality: "analitico", patience: 68, description: "Presidente do Red Bull Bragantino, dirigente com DNA Red Bull de alta performance e dados. Administra o clube com foco em análise e desenvolvimento sustentável. Tem paciência com projetos estruturados e cobra que o Braga seja competitivo entre os melhores do Brasil." },

  // ─── LIGA ARGENTINA ──────────────────────────────────────────────────────
  435: { name: "Jorge Amor Ameal", personality: "diplomatico", patience: 58, description: "Presidente do Club Atlético Boca Juniors, dirigente histórico do clube xeneize. Vive intensamente a rivalidade com o River Plate e cobra que o Boca seja sempre protagonista. Tem paciência moderada e valoriza a identidade guerreira do clube." },
  436: { name: "Maximiliano Romero", personality: "exigente", patience: 50, description: "Presidente do Club Atlético River Plate, um dos maiores clubes da América do Sul. Tem expectativas altíssimas e exige que o Millonario seja protagonista no futebol argentino e sul-americano. A tradição e o tamanho do River demandam excelência constante." },
  433: { name: "Víctor Blanco", personality: "analitico", patience: 62, description: "Presidente do Racing Club, dirigente argentino com gestão profissional. Administra o clube de Avellaneda com visão de longo prazo e foco em títulos. Tem paciência com projetos coerentes e cobra que o Racing seja sempre protagonista no futebol argentino." },
  439: { name: "Fabián Doman", personality: "emocional", patience: 52, description: "Presidente do Club Atlético Independiente, dirigente apaixonado pelo Rojo. Vive intensamente os resultados do clube histórico de Avellaneda. Tem paciência moderada e cobra que o Independiente recupere seu brilho histórico no futebol argentino." },
  437: { name: "Marcelo Moretti", personality: "diplomatico", patience: 60, description: "Presidente do San Lorenzo de Almagro, dirigente com gestão equilibrada. Administra o clube azulgrana com foco na competitividade e na sustentabilidade. Tem paciência com projetos de desenvolvimento e valoriza a identidade cuervo do clube." },
  442: { name: "Sergio Rapisarda", personality: "conservador", patience: 65, description: "Presidente do Vélez Sársfield, dirigente com gestão séria e responsável. Administra o clube de Liniers com foco na competitividade e na formação de jovens. Tem paciência com projetos de longo prazo e valoriza a tradição do clube." },
  444: { name: "Juan Sebastián Verón", personality: "analitico", patience: 65, description: "Presidente do Estudiantes de La Plata, ex-jogador e dirigente apaixonado pelo Pincha. Com background profissional, traz visão moderna ao clube. Valoriza a formação de jovens e cobra que o Estudiantes seja competitivo no futebol argentino." },

  // ─── LIGA MX ─────────────────────────────────────────────────────────────
  569: { name: "Emilio Azcárraga Jean", personality: "exigente", patience: 50, description: "Proprietário do Club América, empresário mexicano do Grupo Televisa. Tem grandes expectativas para o clube mais popular do México e cobra títulos constantemente. Investe fortemente e não aceita que o América não seja protagonista na Liga MX e na Concacaf." },
  570: { name: "Guillermo Álvarez", personality: "diplomatico", patience: 62, description: "Presidente do Cruz Azul, dirigente da cooperativa que administra o clube cementeiro. Tem gestão equilibrada e valoriza a identidade operária do clube. Cobra que o Cruz Azul seja competitivo e representante dos valores históricos da Cooperativa La Cruz Azul." },
  571: { name: "Amaury Vergara", personality: "emocional", patience: 55, description: "Proprietário das Chivas Guadalajara, herdeiro do projeto familiar. Apaixonado pelo clube e pela filosofia de contratar apenas jogadores mexicanos. Valoriza a identidade chivahermana acima de tudo. Cobra que o Rebaño Sagrado seja protagonista na Liga MX." },
  574: { name: "Ernesto Tinajero", personality: "exigente", patience: 50, description: "Presidente dos Tigres UANL, dirigente universitário com grandes ambições. Tigres é uma potência do futebol mexicano e cobra que o clube mantenha esse status. Não aceita mediocridade e exige que a equipe seja sempre competitiva nacional e internacionalmente." },
  573: { name: "José Antonio González Azcárraga", personality: "agressivo", patience: 48, description: "CEO dos Rayados de Monterrey, dirigente do grupo Femsa com altíssimas ambições. Rayados tem um dos maiores orçamentos do México e o presidente cobra retorno total. Pode ser impulsivo quando os resultados frustram as expectativas do clube regiomontano." },
  575: { name: "Roberto Hernández", personality: "diplomatico", patience: 65, description: "Presidente do Santos Laguna, dirigente com gestão equilibrada no clube lagunero. Administra com foco na competitividade e na formação de jovens. Tem paciência com projetos de desenvolvimento e valoriza a identidade do Santos no futebol mexicano." },

  // ─── MLS ─────────────────────────────────────────────────────────────────
  1350: { name: "Chris Klein", personality: "diplomatico", patience: 70, description: "Presidente da LA Galaxy, referência do futebol americano. Administra o clube mais histórico da MLS com visão de longo prazo. Tem paciência com projetos de desenvolvimento e valoriza a identidade da Galaxy como símbolo do futebol nos Estados Unidos." },
  1600: { name: "Jorge Mas", personality: "agressivo", patience: 45, description: "Co-proprietário do Inter Miami CF, com investimento milionário e ambições globais. A chegada de Messi elevou as expectativas astronomicamente. Não aceita desempenho abaixo do esperado e pressiona o corpo técnico. Tem planos de transformar o Miami numa potência do futebol americano." },
  1356: { name: "Brad Sims", personality: "analitico", patience: 65, description: "CEO do New York City FC, representante do City Football Group nos Estados Unidos. Administra o clube com o profissionalismo e a metodologia da organização Manchester City. Tem paciência com projetos coerentes e valoriza o desenvolvimento de jovens talentos americanos." },
  1359: { name: "Merritt Paulson", personality: "emocional", patience: 62, description: "Proprietário do Portland Timbers, apaixonado pelo clube e pela torcida da Army. Vive intensamente os resultados e quer que os Timbers mantenham sua identidade competitiva. Tem paciência moderada e valoriza o futebol ofensivo que caracteriza o clube de Portland." },
  1352: { name: "Adrian Hanauer", personality: "diplomatico", patience: 68, description: "Co-proprietário do Seattle Sounders FC, um dos clubes mais bem organizados da MLS. Tem gestão equilibrada e paciência com projetos coerentes. Valoriza a identidade dos Sounders como potência da MLS e cobra que o clube seja sempre competitivo." },

  // ─── J-LEAGUE ────────────────────────────────────────────────────────────
  308: { name: "Hiroshi Matsubara", personality: "diplomatico", patience: 70, description: "Presidente do Vissel Kobe, dirigente japonês com gestão profissional. O clube teve investimentos significativos e tem ambições de ser referência no futebol japonês. Tem paciência com projetos de longo prazo e valoriza o desenvolvimento consistente." },
  309: { name: "Kunihiko Inoue", personality: "analitico", patience: 68, description: "Presidente do Kashima Antlers, clube mais tradicional do Japão. Administra com rigor e preza pela formação interna de talentos que é marca do clube. Tem paciência com projetos coerentes e cobra que o Kashima mantenha sua posição de referência na J-League." },
  310: { name: "Tomoya Itakura", personality: "exigente", patience: 55, description: "Presidente do Urawa Red Diamonds, clube com a maior torcida do Japão. Tem expectativas altas e cobra que o Urawa seja sempre protagonista na J-League e nas competições asiáticas. Não aceita mediocridade dada a grandeza histórica do clube vermelho." },
  311: { name: "Taro Kishida", personality: "conservador", patience: 65, description: "Presidente do Gamba Osaka, um dos clubes mais tradicionais do futebol japonês. Administra com foco na sustentabilidade e na competitividade na J-League. Tem paciência com projetos de desenvolvimento e valoriza a identidade do futebol organizado." },

  // ─── SAUDI PRO LEAGUE ────────────────────────────────────────────────────
  2932: { name: "Fahad bin Nafel", personality: "exigente", patience: 48, description: "Presidente do Al Hilal FC, maior clube da Arábia Saudita. Tem enormes recursos e expectativas ainda maiores. Não aceita que o Al Hilal não seja dominante na Saudi Pro League e cobra participação nas fases avançadas das competições asiáticas e mundiais." },
  2931: { name: "Musalli Al-Muammar", personality: "exigente", patience: 48, description: "Presidente do Al Nassr FC, clube de Cristiano Ronaldo. Investimentos bilionários elevaram as expectativas do clube amarelo-azul a patamares nunca vistos. Cobra títulos e dominância. A chegada de estrelas mundiais obriga o clube a corresponder com performances de alto nível." },
  2936: { name: "Walid Al-Farraj", personality: "diplomatico", patience: 60, description: "Presidente do Al Ahli SC, clube histórico de Jeddah. Administra com equilíbrio entre ambições e realidade. Tem paciência com projetos de desenvolvimento e cobra que o Al Ahli seja competitivo na Saudi Pro League e represente bem o futebol da cidade." },
  2933: { name: "Ahmed Al-Shubaili", personality: "analitico", patience: 58, description: "Presidente do Al Ittihad FC, um dos quatro grandes da Arábia Saudita. Administra com critério e cobra que o clube seja sempre competitivo. Tem paciência moderada com projetos coerentes e valoriza o desenvolvimento de um projeto vencedor na Saudi Pro League." },

  // ─── BELGIAN PRO LEAGUE ──────────────────────────────────────────────────
  550: { name: "Bart Verhaeghe", personality: "analitico", patience: 68, description: "Presidente do Club Brugge, um dos clubes mais bem organizados da Bélgica. Construiu um modelo de gestão profissional e competitivo. Tem paciência com projetos coerentes e cobra que o Brugge mantenha sua dominância na Pro League belga e presença na Champions League." },
  555: { name: "Wouter Vandenhaute", personality: "diplomatico", patience: 65, description: "Presidente do RSC Anderlecht, o maior clube da Bélgica. Administra o clube histórico com visão de longo prazo e foco em recuperar o prestígio perdido. Tem paciência com o processo de reconstrução e cobra que o Anderlecht volte a ser potência europeia." },
  556: { name: "Pierre François", personality: "conservador", patience: 65, description: "Presidente do Standard Liège, dirigente liégeois com gestão equilibrada. Administra o clube histórico com foco na sustentabilidade. Tem paciência com projetos de desenvolvimento e cobra que o Standard mantenha sua posição de destaque no futebol belga." },
  549: { name: "Ivan De Witte", personality: "diplomatico", patience: 65, description: "Presidente do KAA Gent, um dos clubes mais surpreendentes do futebol belga. Tem gestão profissional e valoriza o desenvolvimento de jovens talentos. Tem paciência com projetos coerentes e cobra que o Gent se mantenha entre os melhores da Bélgica." },
  553: { name: "Peter Croonen", personality: "analitico", patience: 65, description: "Presidente do KRC Genk, clube famoso pela revelação de talentos. Administra com foco em data analytics e desenvolvimento sustentável. Tem paciência com processos estruturados e valoriza a formação de jovens que depois representam o clube nas grandes ligas europeias." },

  // ─── AUSTRIAN BUNDESLIGA ─────────────────────────────────────────────────
  412: { name: "Stephan Reiter", personality: "analitico", patience: 65, description: "CEO do FC Red Bull Salzburg, dirigente com DNA Red Bull de alta performance. Administra o clube com foco em dados e desenvolvimento de jovens que depois representam as demais equipes do grupo. Cobra que o Salzburg domine a Bundesliga austríaca e avance na Europa." },
  410: { name: "Christian Jauk", personality: "diplomatico", patience: 68, description: "Presidente do SK Sturm Graz, dirigente estiriano com gestão equilibrada. Administra o clube com foco na competitividade e na sustentabilidade. Tem paciência com projetos de desenvolvimento e cobra que o Sturm mantenha sua posição no topo do futebol austríaco." },

  // ─── SUPER LEAGUE GREECE ─────────────────────────────────────────────────
  460: { name: "Evangelos Marinakis", personality: "exigente", patience: 50, description: "Presidente do Olympiacos FC, armador grego que controla o maior clube da Grécia. Tem grandes ambições e exige que o Olympiacos domine o futebol grego e seja competitivo na Europa. Investe fortemente e cobra retorno total dos investimentos realizados no clube do Pireu." },
  461: { name: "Giannis Alafouzos", personality: "analitico", patience: 65, description: "Presidente do Panathinaikos FC, dirigente grego com gestão profissional. Administra o clube histórico de Atenas com foco na competitividade. Tem paciência com projetos coerentes e cobra que o Panathinaikos desafie o Olympiacos na Super League grega." },
  462: { name: "Thanos Giannopoulos", personality: "diplomatico", patience: 63, description: "Presidente do AEK Athens FC, dirigente do clube da águia. Administra com equilíbrio e cobra que o AEK seja competitivo tanto na Grécia como na Europa. Tem paciência com projetos de desenvolvimento e valoriza a tradição histórica do clube." },
  463: { name: "Giannis Samaras", personality: "emocional", patience: 55, description: "Presidente do PAOK FC de Salônica, dirigente apaixonado pelo clube do norte da Grécia. Vive intensamente a rivalidade com os clubes atenienses. Cobra que o PAOK seja sempre protagonista na Super League e represente o norte grego com orgulho." },

  // ─── CZECH FIRST LEAGUE ──────────────────────────────────────────────────
  481: { name: "Jaroslav Tvrdík", personality: "exigente", patience: 55, description: "Presidente do SK Slavia Prague, dirigente tcheco ambicioso. Transformou o Slavia numa potência europeia. Não aceita mediocridade e exige que o clube seja dominante na liga tcheca e competitivo nas competições europeias. Investe fortemente e cobra resultados." },
  480: { name: "Daniel Křetínský", personality: "analitico", patience: 65, description: "Dono do AC Sparta Prague, bilionário tcheco com portfólio esportivo europeu. Administra com visão de longo prazo e foco em desenvolvimento. Tem paciência com projetos coerentes e cobra que o Sparta mantenha sua dominância histórica no futebol tcheco." },

  // ─── HNL CROATIA ─────────────────────────────────────────────────────────
  680: { name: "Mirko Barišić", personality: "exigente", patience: 52, description: "Presidente do GNK Dinamo Zagreb, o clube mais bem-sucedido da história croata. Exige que o Dinamo domine o futebol nacional e seja competitivo na Champions League. Tem grandes expectativas e não aceita que o clube perca sua posição dominante." },
  681: { name: "Ivan Bilić", personality: "emocional", patience: 55, description: "Presidente do HNK Hajduk Split, apaixonado pelo clube branco da Dalmácia. A torcida Torcida é uma das mais apaixonadas do mundo e o presidente sente essa pressão. Cobra que o Hajduk desafie o Dinamo e recupere seus títulos históricos no futebol croata." },

  // ─── SWISS SUPER LEAGUE ──────────────────────────────────────────────────
  1101: { name: "David Degen", personality: "analitico", patience: 65, description: "Presidente do FC Basel 1893, ex-jogador com visão moderna do futebol. Administra o clube com foco em desenvolvimento de jovens e competitividade europeia. Tem paciência com projetos coerentes e cobra que o Basel seja referência no futebol suíço." },
  1107: { name: "Steve von Bergen", personality: "diplomatico", patience: 65, description: "Presidente do BSC Young Boys, ex-jogador e dirigente equilibrado. Administra o clube com foco na sustentabilidade e na competitividade na Super League suíça. Tem paciência com projetos de desenvolvimento e cobra que o YB mantenha sua dominância recente." },
  1102: { name: "Ancillo Canepa", personality: "conservador", patience: 67, description: "Presidente do FC Zürich, o clube mais antigo da Suíça. Administra com tradição e valoriza o desenvolvimento sustentável. Tem paciência com projetos de longo prazo e cobra que o Zürich seja sempre competitivo na Super League e na Europa." },
  1103: { name: "Didier Fischer", personality: "diplomatico", patience: 65, description: "Presidente do Servette FC de Genebra, um dos clubes mais históricos da Suíça. Administra com equilíbrio e cobra competitividade na Super League. Tem paciência com processos de desenvolvimento e valoriza a tradição do clube genebrino." },
  1104: { name: "Angelo Renzetti", personality: "conservador", patience: 65, description: "Presidente do FC Lugano, clube do Ticino suíço com identidade italiana. Administra com gestão familiar e foco na sustentabilidade. Tem paciência com projetos de desenvolvimento e cobra que o Lugano mantenha sua competitividade na Super League suíça." },
  1106: { name: "Matthias Hüppi", personality: "analitico", patience: 65, description: "Presidente do FC St. Gallen, ex-jornalista com visão profissional do futebol. Administra o clube histórico do leste suíço com critério e dados. Tem paciência com projetos coerentes e cobra que o clube seja competitivo na Super League suíça." },
  1108: { name: "Peter Stadelmann", personality: "conservador", patience: 65, description: "Presidente do Grasshopper Club Zürich, o mais antigo clube de futebol da Suíça. Administra com respeito à história e foco na recuperação do clube ao futebol de elite. Tem paciência com processos de reestruturação e valoriza a tradição centenária do Grasshopper." },
  1105: { name: "Alain Joseph", personality: "diplomatico", patience: 63, description: "Presidente do FC Lausanne-Sport, clube histórico do Vaud suíço. Administra com equilíbrio financeiro e foco na competitividade. Tem paciência com processos de desenvolvimento e cobra que o Lausanne mantenha sua presença na Super League suíça." },

  // ─── LIGA 1 ROMANIA ──────────────────────────────────────────────────────
  626: { name: "Gigi Becali", personality: "agressivo", patience: 35, description: "Proprietário do FCSB, uma das figuras mais controversas do futebol europeu. Empresário e político romeno que não tem papas na língua. Interfere diretamente nas escalações e nas decisões táticas. Extremamente impulsivo e pode demitir um técnico após qualquer sequência negativa. Sempre polêmico e imprevisível." },
  627: { name: "Neluțu Varga", personality: "exigente", patience: 50, description: "Presidente do CFR Cluj, empresário romeno com ambições de dominar o futebol romeno. Exige que o CFR seja sempre protagonista na Liga 1 e competitivo na Europa. Cobra resultados constantemente e não tem muita paciência com sequências negativas." },

  // ─── SUPERLIGA SERBIA ────────────────────────────────────────────────────
  402: { name: "Zvonko Šapić", personality: "exigente", patience: 50, description: "Presidente da FK Crvena zvezda (Red Star Belgrade), um dos maiores clubes dos Bálcãs. Tem grandes expectativas e exige que o clube domine o futebol sérvio e seja competitivo na Europa. A história gloriosa do clube impõe padrões altíssimos de desempenho." },
  403: { name: "Mihajlo Pjanović", personality: "diplomatico", patience: 60, description: "Presidente do FK Partizan, clube histórico de Belgrado. Administra com foco na competitividade e na tradição do clube preto-branco. Tem paciência com projetos coerentes e cobra que o Partizan desafie a Estrela Vermelha pela supremacia do futebol sérvio." },

  // ─── SUPERLIGAEN DENMARK ─────────────────────────────────────────────────
  384: { name: "Flemming Østergaard", personality: "analitico", patience: 65, description: "Presidente do FC Copenhagen, clube mais bem organizado do futebol nórdico. Administra com profissionalismo e foco em competitividade europeia. Tem paciência com projetos coerentes e cobra que o Copenhagen mantenha sua posição de potência no futebol escandinavo." },
  390: { name: "Jan Bech Andersen", personality: "conservador", patience: 65, description: "Presidente do Brøndby IF, clube histórico de Copenhague. Administra com foco na sustentabilidade e na competitividade na Superligaen. Tem paciência com projetos de desenvolvimento e cobra que o Brøndby desafie o FC Copenhagen pela liderança do futebol dinamarquês." },
  388: { name: "Rasmus Ankersen", personality: "analitico", patience: 68, description: "Co-presidente do FC Midtjylland, pioneiro em data analytics no futebol. Construiu um dos modelos de análise mais sofisticados do futebol europeu. Tem grande paciência com projetos estruturados e valoriza a eficiência e a inovação na gestão esportiva." },

  // ─── ELITESERIEN NORWAY ──────────────────────────────────────────────────
  357: { name: "Ivar Koteng", personality: "conservador", patience: 68, description: "Presidente do Rosenborg BK, o maior clube da Noruega. Administra com responsabilidade e foco na manutenção da relevância histórica do clube. Tem paciência com projetos de longo prazo e cobra que o Rosenborg seja sempre o clube de referência do futebol norueguês." },
  352: { name: "Frode Thomassen", personality: "diplomatico", patience: 65, description: "Presidente do FK Bodø/Glimt, clube que fez história ao vencer o futebol europeu de surpresa. Administra o crescimento do clube ártico com equilíbrio e determinação. Tem paciência com o processo de consolidação e cobra que o Glimt mantenha seu alto nível." },

  // ─── ALLSVENSKAN SWEDEN ──────────────────────────────────────────────────
  364: { name: "Andreas Georgson", personality: "analitico", patience: 65, description: "Presidente do Malmö FF, o clube sueco de maior tradição europeia. Administra com profissionalismo e foco em competitividade. Tem paciência com projetos coerentes e cobra que o Malmö mantenha sua dominância na Allsvenskan e presença nas copas europeias." },
  362: { name: "Robert Lundström", personality: "diplomatico", patience: 63, description: "Presidente do AIK Stockholm, clube histórico da capital sueca. Administra com equilíbrio e valoriza a identidade negra e amarela do clube. Tem paciência com processos de desenvolvimento e cobra que o AIK seja sempre competitivo na Allsvenskan." },

  // ─── UKRAINIAN PREMIER LEAGUE ────────────────────────────────────────────
  385: { name: "Rinat Akhmetov", personality: "exigente", patience: 55, description: "Presidente do Shakhtar Donetsk, um dos homens mais ricos da Ucrânia. Investiu massivamente no clube e transformou o Shakhtar numa potência europeia. Tem expectativas altíssimas e cobra que o clube mantenha seu nível de competitividade mesmo nas circunstâncias adversas do futebol ucraniano." },
  386: { name: "Igor Surkis", personality: "diplomatico", patience: 62, description: "Presidente do Dynamo Kyiv, o clube mais histórico da Ucrânia. Administra o clube com senso de responsabilidade histórica. Tem paciência com projetos coerentes e cobra que o Dynamo seja sempre competitivo no futebol ucraniano e europeu, mantendo o legado glorioso do clube." },
};

const PATIENCE_BY_PERSONALITY: Record<string, number> = {
  conservador: 70,
  diplomatico: 68,
  analitico: 65,
  emocional: 52,
  exigente: 48,
  agressivo: 42,
};

const COUNTRY_NAMES: Record<string, string[]> = {
  Brazil: ["Carlos Eduardo Menezes", "Roberto Alves", "Fábio Rodrigues", "Marcelo Santos", "André Carvalho", "Paulo Henrique Costa", "Luiz Fernando Souza", "Thiago Barbosa"],
  England: ["Richard Thompson", "Michael Davies", "James Harrison", "Robert Clarke", "Andrew Wilson", "David Holloway", "Peter Ashworth", "Jonathan Blake"],
  Spain: ["Alejandro García", "Carlos Martínez", "Miguel Ángel López", "Francisco Romero", "Javier Sánchez", "Antonio Fernández", "Rafael Moreno", "Luis Castillo"],
  Italy: ["Luca Colombo", "Marco Rossi", "Giorgio Ferrari", "Alessandro Bruno", "Francesco Ricci", "Roberto Conti", "Stefano Palermo", "Davide Esposito"],
  Germany: ["Klaus Werner", "Jürgen Hoffmann", "Hans Schäfer", "Stefan Bauer", "Michael Koch", "Thomas Richter", "Andreas Schulz", "Markus Braun"],
  France: ["Jean-Pierre Moreau", "Philippe Lambert", "Michel Dupont", "François Martin", "Bernard Leroy", "Thierry Simon", "Alain Petit", "Christophe Girard"],
  Portugal: ["João Ferreira", "Rui Pinto", "Pedro Sousa", "Nuno Almeida", "Miguel Costa", "Luís Rodrigues", "António Silva", "Carlos Figueiredo"],
  Netherlands: ["Jan van der Berg", "Pieter Visser", "Willem de Groot", "Hendrik Bakker", "Johan Smit", "Dirk Muller", "Koen Jansen", "Bas van Dijk"],
  Argentina: ["Diego Rodríguez", "Martín González", "Pablo Álvarez", "Gustavo Pérez", "Hernán López", "Alejandro Silva", "Nicolás Castro", "Fabián Torres"],
  Mexico: ["Alejandro Torres", "Carlos Morales", "Roberto Gutiérrez", "Miguel Flores", "Juan Manuel Reyes", "Rodrigo Vargas", "Luis Medina", "Ernesto Pacheco"],
  Turkey: ["Ahmet Yilmaz", "Mehmet Demir", "Mustafa Kaya", "Ibrahim Celik", "Hasan Güler", "Ali Özdemir", "Emre Polat", "Osman Arslan"],
  Russia: ["Alexei Petrov", "Dmitri Volkov", "Igor Sokolov", "Nikolai Kuznetsov", "Sergei Morozov", "Vladimir Popov"],
  "United States": ["Robert Johnson", "Michael Davis", "James Anderson", "William Clarke", "Christopher Martin", "Matthew Harris", "Kevin Wilson"],
  China: ["Wei Zhang", "Jian Li", "Ming Wang", "Hao Chen", "Lei Liu", "Gang Zhao"],
  Japan: ["Hiroshi Tanaka", "Kenji Suzuki", "Yuki Yamamoto", "Takeshi Sato", "Makoto Watanabe", "Shinji Kimura"],
  Scotland: ["Alistair MacDonald", "Cameron Fraser", "Duncan McLean", "Iain Robertson", "Angus Campbell"],
  Belgium: ["Marc Devos", "Pierre Lebrun", "Thierry Claes", "Erik Janssen", "Luc Verbeke"],
  Colombia: ["Carlos Aristizabal", "Andrés Mejía", "Jorge Rendón", "Mauricio Pedraza", "Felipe Vargas"],
  Chile: ["Rodrigo Fuentes", "Pablo Herrera", "Sebastián Moya", "Cristóbal Lagos", "Felipe Sandoval"],
  Uruguay: ["Diego Fernández", "Pablo Méndez", "Andrés Suárez", "Rodrigo Pereyra", "Gustavo Giménez"],
  Austria: ["Gerhard Müller", "Johann Weber", "Franz Bauer", "Karl Huber", "Peter Gruber"],
  Greece: ["Nikos Papadopoulos", "Dimitris Kostas", "Yannis Stavros", "Petros Alexiou", "Kostas Dimos"],
  Serbia: ["Dragan Nikolić", "Marko Petrović", "Stefan Jovanović", "Vladimir Ilić", "Nemanja Đorđević"],
  Croatia: ["Ivan Marković", "Ante Horvat", "Mario Kovač", "Tomislav Jurić", "Stjepan Blažević"],
  Switzerland: ["Hans Meier", "Peter Zimmermann", "Daniel Brunner", "Marco Steiner", "Andreas Keller"],
  Romania: ["Ion Popescu", "Gheorghe Constantin", "Andrei Marin", "Radu Ionescu", "Mihai Dumitru"],
  Denmark: ["Lars Andersen", "Niels Jensen", "Jens Nielsen", "Morten Christensen", "Anders Pedersen"],
  Norway: ["Erik Johansen", "Lars Olsen", "Anders Berg", "Kristian Larsen", "Tor Hansen"],
  Sweden: ["Lars Svensson", "Johan Eriksson", "Anders Lindqvist", "Erik Persson", "Marcus Nilsson"],
  Ukraine: ["Andriy Kovalenko", "Oleksiy Shevchenko", "Vasyl Moroz", "Mykola Petrenko", "Taras Bondar"],
  default: ["James Miller", "Carlos Oliveira", "Marco Ricci", "Pierre Dupont", "Heinrich Müller", "Alejandro Ruiz", "Ahmad Al-Hassan"],
};

const PERSONALITY_DESCRIPTIONS_PT: Record<string, string> = {
  conservador: "Presidente conservador e criterioso, prefere estabilidade ao risco. Dá suporte ao técnico enquanto vê progressão e cobra resultados consistentes. Gerencia o clube com prudência financeira e evita decisões impulsivas. Tem paciência com ciclos naturais do futebol, mas cobra comprometimento constante.",
  agressivo: "Presidente exigente e impaciente, espera resultados imediatos dos investimentos. Pode ser impulsivo em momentos de crise e pressiona o técnico constantemente. Tem dificuldade em aceitar sequências negativas e pode tomar decisões abruptas. No entanto, quando as coisas vão bem, celebra generosamente os resultados alcançados.",
  analitico: "Presidente analítico que toma decisões baseadas em dados e indicadores de desempenho. Avalia o trabalho do técnico com critério e objetividade. Dá suporte ao projeto enquanto os números justificam as escolhas táticas. Tem aversão a decisões impulsivas e valoriza planejamento de longo prazo.",
  emocional: "Presidente apaixonado que vive intensamente cada resultado da equipe. Pode ser impulsivo quando as coisas não vão bem, mas é extremamente generoso nos momentos de vitória. Valoriza conexão com os torcedores e espera que o técnico entenda a alma do clube. Tem sentimentos fortes sobre o estilo de jogo e a identidade da equipe.",
  diplomatico: "Presidente diplomático que navega bem entre torcida, jogadores e imprensa. Tem paciência com projetos de longo prazo e valoriza o comprometimento da equipe. Gere conflitos internos com habilidade e raramente entra em confronto público. Cobra resultados, mas entende que o futebol tem ciclos e dá tempo ao técnico para trabalhar.",
  exigente: "Presidente altamente exigente que não aceita mediocridade. Cobra alta performance em todas as competições e tem expectativas proporcionais ao potencial do clube. Analisa cada detalhe e questiona decisões táticas quando os resultados não satisfazem. Leal aos que entregam, mas implacável com quem decepciona.",
};

function getRandomItem<T>(arr: T[], seed: number): T {
  return arr[Math.abs(seed) % arr.length];
}

const PERSONALITIES: PersonalityStyle[] = ["conservador", "diplomatico", "analitico", "emocional", "exigente", "agressivo"];

export function getClubPresident(clubId: number): ClubPresidentData | null {
  return CLUB_PRESIDENTS[clubId] ?? null;
}

export function buildFallbackPresident(
  clubId: number,
  clubCountry?: string,
  personality?: string,
): ClubPresidentData {
  const pers = (personality as PersonalityStyle | undefined) ?? PERSONALITIES[Math.abs(clubId) % PERSONALITIES.length];
  const patience = PATIENCE_BY_PERSONALITY[pers] ?? 60;
  const countryNames = COUNTRY_NAMES[clubCountry ?? ""] ?? COUNTRY_NAMES.default;
  const name = getRandomItem(countryNames, clubId);
  const description = PERSONALITY_DESCRIPTIONS_PT[pers] ?? PERSONALITY_DESCRIPTIONS_PT.diplomatico;
  return { name, personality: pers, patience, description };
}
