export interface Country {
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "Brasil", flag: "🇧🇷" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Espanha", flag: "🇪🇸" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "França", flag: "🇫🇷" },
  { name: "Alemanha", flag: "🇩🇪" },
  { name: "Itália", flag: "🇮🇹" },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Holanda", flag: "🇳🇱" },
  { name: "Bélgica", flag: "🇧🇪" },
  { name: "Croácia", flag: "🇭🇷" },
  { name: "Sérvia", flag: "🇷🇸" },
  { name: "Polônia", flag: "🇵🇱" },
  { name: "Dinamarca", flag: "🇩🇰" },
  { name: "Suécia", flag: "🇸🇪" },
  { name: "Noruega", flag: "🇳🇴" },
  { name: "Suíça", flag: "🇨🇭" },
  { name: "Áustria", flag: "🇦🇹" },
  { name: "Escócia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Irlanda", flag: "🇮🇪" },
  { name: "Grécia", flag: "🇬🇷" },
  { name: "Turquia", flag: "🇹🇷" },
  { name: "Ucrânia", flag: "🇺🇦" },
  { name: "Rep. Tcheca", flag: "🇨🇿" },
  { name: "Eslováquia", flag: "🇸🇰" },
  { name: "Hungria", flag: "🇭🇺" },
  { name: "Romênia", flag: "🇷🇴" },
  { name: "Rússia", flag: "🇷🇺" },
  { name: "Marrocos", flag: "🇲🇦" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Nigéria", flag: "🇳🇬" },
  { name: "Costa do Marfim", flag: "🇨🇮" },
  { name: "Gana", flag: "🇬🇭" },
  { name: "Camarões", flag: "🇨🇲" },
  { name: "Egito", flag: "🇪🇬" },
  { name: "África do Sul", flag: "🇿🇦" },
  { name: "Uruguai", flag: "🇺🇾" },
  { name: "Colômbia", flag: "🇨🇴" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "Equador", flag: "🇪🇨" },
  { name: "Peru", flag: "🇵🇪" },
  { name: "Paraguai", flag: "🇵🇾" },
  { name: "Bolívia", flag: "🇧🇴" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "México", flag: "🇲🇽" },
  { name: "EUA", flag: "🇺🇸" },
  { name: "Japão", flag: "🇯🇵" },
  { name: "Coreia do Sul", flag: "🇰🇷" },
  { name: "Austrália", flag: "🇦🇺" },
  { name: "Arábia Saudita", flag: "🇸🇦" },
  { name: "Irã", flag: "🇮🇷" },
  { name: "China", flag: "🇨🇳" },
];
